### ISSUE TITLE
Lokalizacja plików programu

### ISSUE THREAD

**Issue by pavbaranov** [juliagoda/qfaktury#1]
Po pierwsze dzięki za Twoją pracę.
Rozważ jednak, czy lokalizacja plików programu w /usr/local/XYZ jest sensowna. W zasadzie jedyną "współczesną" dystrybucją, która pliki programów trzyma w /usr/local/ jest Debian, który już w Unstable (SID) również przeszedł na lokalizację znaną innym dystrybucjom, czyli /usr/XYZ.
W przypadku PKGBUILDu - nie ma problemu, sprawę załatwiam sedem (m.in.). Nie wiem jednak, czy tak łatwo to zrobić w innych dystrybucjach. Skoro jednak tylko jedna dystrybucja ma /usr/local/, to może sensownie jest zmienić /usr/local na /usr w qfaktury.pro oraz tak samo w QFaktury.desktop?

**Comment by juliagoda** [comment]
Oczywiście, już zrobione. Gdyby jednak nadal się coś nie zgadzało, to jestem otwarta na propozycje i zmiana będzie wykonana jak najszybciej. W innych sprawach poza tą kwestią zajmę się po najbliższym poniedziałku, tymczasem można tu pisać, a odezwę się i poprawię co trzeba od wspomnianego czasu. Dzięki za uwagę i za testowanie aplikacji, co znacznie ułatwia rozwój i odciąża dodatkowo od wykonywania testów w mniejszym lub większym stopniu. Tymczasem życzę Wesołych Świąt

**Comment by pavbaranov** [comment]
Jagoda, to musisz jeszcze zmienić ten plik: https://github.com/juliagoda/qfaktury/blob/master/ReadMe.txt bo są tu stare lokalizacje.
Ja tymczasem "wracam" do poprzedniej wersji PKGBUILDu ;)

Swoją drogą - nie znam się - czy plik *.desktop nie może być generowany na podstawie tego co jest w *.pro? Konfigurując kompilację za pomocą qmake jestem w stanie przekazać programowi m.in. lokalizację plików programu (popularny prefix). Jeśli zatem ktoś zmieniałby na /usr/local/* to otrzymałby qfaktury.desktop z danymi czerpanymi z *.pro itd... W pliku *.txt mogłaby się pojawić natomiast jedynie ogólna informacja "co z tym robić" :)

Programik - działa ok. Miłych Świąt Wam życzę i mam nadzieję - w końcu - do rychłego zobaczenia (jestem Ci coś winien ;)).

**Comment by juliagoda** [comment]
Zapomniany plik tekstowy poprawiony a i niestety nie, kiedyś próbowałam i teraz dla pewności przetestowałam jeszcze raz, ale plik się sam nie generuje.

Dzięki za wszystko. Wesołych Świąt i dużo zdrowia :)
