### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by travnick** [juliagoda/qfaktury#10]
Proszę o kontakt mailowy (na adres który mam podany w profilu) - niestety nie znalazłem innej opcji kontaktu ;]

**Comment by sirlucjan** [comment]
Sugerowałbym przeczytanie wiadomości przed jej wysłaniem - tak do końca nie wiadomo, co poeta miał na myśli.  :]

P.S Nie wiedziałem, że "Issues" służy do nawiązywania kontaktu z autorem projektu ale w sumie co ja tam wiem ...

Jeśli chcesz wprowadzać poprawki - od tego masz "pull request". Jeśli autorka projektu uzna, że Twoje poprawki są godne uwagi, to włączy je do głównego projektu. Jeśli autorka nie wprowadzi Twoich zmian do głównego projektu, możesz rozwijać swój projekt równolegle. Tak działa github (a raczej tak działa dowolna platforma bazująca na rozproszonym systemie kontroli wersji git) i między innymi do tego właśnie służy forkowanie repozytoriów.

**Comment by juliagoda** [comment]
Tak, napiszę bo nie szkodzi mi się zapoznać z tym, co chcesz zaoferować, jednak zwykle robi się tak, że wprowadzasz zmiany na swoim forku i wysyłasz pull request, którego mogę zaakceptować lub nie. Jeśli nie zgadzasz się z moją opinią, to możesz mnie przekonać do swojego zdania i jeżeli okaże się, że ma sens i jest bardziej wydajny niż mój pomysł w przypadku jakiegoś commit'u, do którego nie mam przekonania. Zarazem robisz swój projekt i zarazem pomagasz mi w jego rozwoju, tak jak zresztą chciałeś. Tymczasem muszę zamknąć wątek, bo nie dotyczy żadnego błędu i gdyby było to forum, wylądowałoby to w koszu, więc dobrze, jakbyś tego więcej nie robił.

**Comment by travnick** [comment]
@sirlucjan nie wiem jak doszło do tych literówek - poprawiłem. 
Jeżeli autor nie udostępnia innej drogi to Issues pozostaje jedyną opcją kontaktu.

@juliagoda Tak, zwykle wystarcza, jednak chciałbym porozmawiać o projekcie, żeby prowadzić prace w sposób zorganizowany. Na to niestety pull requestów nie ma.

Gdyby było forum to tam można by prowadzić różne dyskusje o projekcie. Najczęściej prowadząc projekt zespołowy (czym poniekąd jest udostępnianie kodu na githubie) warto jest udostępnić jakąś formę kontaktu z aktualnymi developerami.

**Comment by sirlucjan** [comment]
Jeśli chcesz założyć nieoficjalne forum (bez tak zwanej afiliacji) dotyczące projektu, to nikt tego nie zabrania.  Pull request jak najbardziej pozwala na dyskusję - pierwszy lepszy przykład: https://github.com/clementine-player/Clementine/pull/5617. W komentarzach można prowadzić dyskusje na temat sensu wprowadzanych zmian oraz sugerowanie ewentualnych poprawek,

Jeśli chcesz wprowadzać zmiany, wprowadzanie ich w sforkowanym projekcie oraz wysyłanie pull requestów jest najskuteczniejszą opcją, jeśli autor kodu nie udostępnia (i jak widać, nie ma zamiaru tego uczynić) kontaktu. 

Natomiast umieszczenie projektu na githubie w żaden sposób nie czyni go projektem zespołowym - spora część projektów umieszczanych na "gicie" (github, gitlab) to projekty jednoosobowe, który rozwija sam autor - a społeczność wspiera takie programy właśnie przy pomocy pull requestów.  System kontroli wersji wspiera pracę zespołową ale ta nie jest celem jego istnienia.

**Comment by travnick** [comment]
Nie chodzi mi o nieoficjalne forum. Chciałem porozmawiać z osobą (czy też osobami) utrzymującą projekt na jego temat.

Pull request to dyskusja o już wprowadzonych zmianach (wykonanej pracy) a nie o przyszłych zmianach.
W dużych projektach są rozpisane zadania, bugi, standard pisania kodu, są listy dyskusyjne. Pull requesty są skutkiem planów. Dyskutuje się w nich nad konkretną implementacją a nie w ogóle nad sensem wykonanej pracy - czego chciałbym uniknąć, bo szkoda na to naszego wspólnego czasu.

Jeżeli właściciel repozytorium nie pisze wprost, że nie ma zamiaru z nikim współpracować/rozmawiać etc. to domyślnym założeniem jest, że skoro umieszcza kod w miejscu publicznym, do którego wszyscy mają dostęp to liczy się z tym, że znajdzie się ktoś, kto chciałby również rozwijać ten projekt w sposób zorganizowany.

Naturalnym wydaje mi się założenie, że jeżeli jest taka możliwość to zorganizowana praca zespołowa przyniesie wszystkim więcej korzyści niż pisanie czegoś na podstawie własnego widzimisię i pytanie czy takie zmiany są ok (czym jest pull request bez zdefiniowanych zasad współpracy w projekcie i bez żadnego planu)
Projekt jest mały i całkowicie rozumiem, że nikt nie rozpisywał się o tym jakie zasady panują w projekcie.

**Comment by juliagoda** [comment]
Zasady w projekcie panują takie jak na niemal każdym projekcie na tej stronie i nie planuję wprowadzać nic nowego. Ktoś wymyślił pull request, by nie trzeba było ryzykować wpuszczaniem kogoś do głównego projektu, kogo się nie zna, a jak twoja zmiana ma polegać np. na kastracji programu to wybacz. Ten program kosztował mnie czas, za który nikt mi jakby nie patrzeć nie płaci, więc zaryzykować nie zamierzam. Po coś w końcu sforkowałeś ten projekt, no chyba że ma tylko twoje całe repo imponować samą ilością. Nie masz zamiaru czasu marnować na omawianie programu, ale na rozpisywanie się o kontakt masz i kłótnie też masz, bo skończyć dyskusji jakoś nie możesz. Adresu e-mail bezpośrednio nie podaję i podawać zamiaru nie mam z wielu powodów, do czego mam całkowite prawo (chyba, ze ktoś je znajdzie, ale to co innego, bo zakładam, że ten ktoś jest ogarnięty). Zanim cokolwiek z góry założysz, zapoznaj się z narzędziami na tej stronie, które ułatwiają życie. Inne sprawa to inna twoja interpretacja słowa organizacja i właśnie specjalnie do tego ktoś mądry stworzył dla tej strony wiele przemyślanych opcji, by takich widzimisię i problemów unikać, radzę się z nimi zapoznać i skorzystać.

**Comment by travnick** [comment]
Nie mówię o wpuszczaniu do projektu, pull requesty są jak najbardziej ok. Ale nie są one miejscem na rozmowę o projekcie.

Moim zamiarem nie była żadna kłótnia i póki co mam nadzieję, że jest to wymiana poglądów.
Przyszedłem tutaj z myślą "Oo, ciekawy projekt, przyda mi się jego funkcjonalność, mogę dopisać kilka brakujących mi (i prawdopodobnie innym) rzeczy, widzę, że można coś tutaj ulepszyć poprawić i wszyscy na tym skorzystają więc skontaktuję się z autorem i porozmawiam o przyszłości projektu".

Proszę o kontakt bo jak @sirlucjan słusznie zauważył, issuy nie są do rozmawiania o projekcie, pull requesty również. na githubie brakuje forum. Jest zakładka Projects ale tylko właściciel repozytorium może tam coś dodawać. Tak więc bardzo chętnie użyłbym innej opcji ale github po prostu takiej nie ma.

Co do kastracji - tak miałem pomysł, żeby wyrzucić zdaje się duplikat, ale Twój komentarz na temat kompatybilności wstecznej jest jak najbardziej sensowny.

Pisałem, że nie chcę marnować czasu na robienie zmian które są bez sensu bądź są szkodliwe (typu wycięcie funkcjonalności duplikatu). O rozmowę o projekcie i jakimś planie chodzi mi od początku. Dlatego chciałem się z Tobą skontaktować.
