### ISSUE TITLE
Memory leak in CustomPayment dtor.

### ISSUE THREAD

**Issue by travnick** [juliagoda/qfaktury#11]
https://github.com/juliagoda/qfaktury/blob/27fd7413b7c07401e67257aaa27824b73c0faf36/src/CustomPayment.cpp#L22
It loses information about any allocated data handled by `custPaymData` so in result:
https://github.com/juliagoda/qfaktury/blob/27fd7413b7c07401e67257aaa27824b73c0faf36/src/CustomPayment.cpp#L23

`custPaymData` is always 0 (nullptr) here and no object is deleted.

**Comment by juliagoda** [comment]
Zamykam. To jest zabezpieczenie dodatkowe w destruktorze, by do wycieku nie dochodziło. Jeśli przed wyjściem z programu jakiś pointer wskazuje na niepusty adres w pamięci i spróbujemy go zwolnić za pomocą delete, dojdzie do wycieku. Równa się zero zeruje wskaźnik i pozwala na bezpieczne wyjście z programu. Musiałam ten trick wprowadzić dla instancji MainWindow w gałęzi KF5 specjalnie dla KXmlGuiWindow, aby program się nie wywalał i nie wskazywał na destruktor.

**Comment by travnick** [comment]
wyciek to niezwalnianie pamięci, do którego dochodzi przez wymienionego ifa, który trafi informacje o adresie zaalokowanej pamięci.

Po dokładniejszym przyjrzeniu się widzę, że tutaj
https://github.com/juliagoda/qfaktury/blob/f9394f49405205fbfb839d6aca8b7a5a4e94c9e3/src/Invoice.cpp#L1206
jest alokowana cała klasa `CustopPayment`. Poniżej są używane dane z `custPaymData` jednak nie widzę powodu, żeby miało coś tutaj wylatywać. Bo z tego co widzę pola są i tak kopiowane.
Poza tym nie wygląda na to, żeby alokacja na stercie była w tym przypadku w ogóle potrzebna zarówno do `custPaymData` jak i `CustopPayment` w powyższym pliku.

Co masz na myśli przez wskazywanie (programu?) na destruktor?
