### ISSUE TITLE
Memory leak in EmailWindow sendMail and dtor.

### ISSUE THREAD

**Issue by travnick** [juliagoda/qfaktury#12]
If `sendMail()` is called mode than once then there is a memory leak.
https://github.com/juliagoda/qfaktury/blob/12b74bcc2df387bb5fc3b42a44b9f1255679a171/src/SimpleSmtp_SSL_QT5/smtp_attachements/mainwindow.cpp#L40

In dtor there is also memory leak caused by
https://github.com/juliagoda/qfaktury/blob/12b74bcc2df387bb5fc3b42a44b9f1255679a171/src/SimpleSmtp_SSL_QT5/smtp_attachements/mainwindow.cpp#L184

**Comment by juliagoda** [comment]
Zamykam. Wysyłanie email działa raz za razem i po ponownym naciśnięciu na "Wyślij" i po ponownym wygenerowaniu okna. Mogło nie działać dotychczasowo, ale wczoraj były wprowadzane zmiany.

**Comment by travnick** [comment]
Wysyłanie może działać, nie zmienia to tego, że obiekty `Smtp` (wraz z ich połączeniami) nie są nigdy zwalniane (znaczy dopiero przy zamknięciu programu przez system)
