### ISSUE TITLE
Integracja z bazą REGON

### ISSUE THREAD

**Issue by ad-m** [juliagoda/qfaktury#19]
Hej,
Nie wykorzystuje oprogramowania, nie prowadzę firmy, ale kibicuje otwartym inicjatywom. Nie zauważyłem w projekcie integracji z bazą REGON. Zatem zgłaszam, że w Polsce [istnieje API dla bazy REGON](http://bip.stat.gov.pl/dzialalnosc-statystyki-publicznej/rejestr-regon/interfejsyapi/jak-skorzystac-informacja-dla-podmiotow-komercyjnych/), co pozwala na wypełnianie nazw / adresów kontrahentów na podstawie NIP/REGON/KRS. 

W razie problemów z dostępem do API lub integracją - służę uprzejmie.

Z poważaniem,

**Comment by juliagoda** [comment]
Tak, w tej sytuacji nawet komunikowałam się i mam zamiar to wprowadzić. Moja otrzymana odpowiedź:

"Dzień dobry!

Przesyłam Pani  link do strony GUS z informacjami o dostępie do danych rejestrowych REGON poprzez usługę sieciową -Interfejsy API - Informacja dla podmiotów komercyjnych.
  W Pani przypadku,(pisze Pani, iż nie prowadzi firmy) też udostępnimy konto do usługi   BIR1(dostęp do danych rejestru Regon) w zakresie jak dla podmiotów komercyjnych."

Dalszy ciąg wiadomości to na czym to polega, jakie zaszły modernizacje w ostatnich latach oraz załączniki do wypełnienia. Prace na github wznawiam od środy 27-ego. W razie problemów z wdrożeniem tej funkcji z pewnością się odezwę. Dzięki wielkie za pomysły
