### ISSUE TITLE
Brak możliwości drukowania

### ISSUE THREAD

**Issue by pavbaranov** [juliagoda/qfaktury#2]
Nie wiem, w której wersji, ale pomiędzy pierwszymi wersjami 0.7.0rc, a obecną rc4 "zgubił" się gdzieś jakiś plik *.css, przez co drukowanie z programu nie jest możliwe.

Z jakiegoś powodu program chce pliku black.css w lokalizacji ~/.local/share/flatpak/exports/share/qfaktury/templates/
Katalog ~/.local/share/flatpak jest katalogiem, w którym flatpak trzyma swoje dane, ale nie jest to miejsce na templatki dla QFaktur, zwłaszcza takich, które nie są instalowane przez flatpak.
Sprawdziłem wszystkie wersje od rc1 do rc4, żadna z nich nie drukuje. Jeśli instalacja jest na "starej" (czyt. Qt4) wersji - program drukuje. Wersje rc3 i rc4 pokazują brak tych templatek w powyższej lokalizacji. 
Po "ręcznym" utworzeniu powyższego katalogu oraz skopiowaniu (dowiązaniu) plików *.css z katalogu /usr/share/qfaktury/templates/ - program drukuje.

Flatpak nie mam zainstalowanego.

**Comment by juliagoda** [comment]
Do tej pory stosowałam z dokumentacji Qt5: QStandardPaths::standardLocations(QStandardPaths::AppDataLocation).at(1) ze strony http://doc.qt.io/qt-5/qstandardpaths.html, który u mnie dawał wynik ścieżki: /usr/share/nazwa_aplikacji czyli qfaktury (inne dwie opcje z trzech to "~/.local/share/APPNAME" oraz "/usr/local/share/APPNAME", z czego wynika że w tym przypadku musiało skorzystać z opcji numer 1, która u mnie byłaby pod innym indeksem mimo że też mam linux'a), więc tym razem dodaję "na sztywno" ścieżkę /usr/share/qfaktury i zobaczymy jaki da efekt

**Comment by pavbaranov** [comment]
Efekt dało dobry ;)
Poprzednia wersja (0.7.0rc4.0.g9c22b0f) w istocie tworzyła ścieżkę /usr/share/qfaktury/, w której był m.in. templates z plikami *.css. Tyle, że jakoś tego aplikacja nie chciała widzieć i szukała w owym lokalnym "flatpaku".
Wersja 0.7.0rc4.1.ge02d99e radzi sobie bez problemu bez niego.

**Comment by juliagoda** [comment]
Tworzyła według ustawionej ścieżki przedstawionej w pliku .pro, jednak do odwoływania się dalej w kodzie program używał i nadal używa takiej zmiennej jak appPath w pliku Settings.h z zawartością wyżej przeze mnie podaną (wcześniej to był enum z QStandardPaths). Nie było jasno w dokumentacji przedstawione pod którym indeksem dla linux'a kryje się dana zawartość z listy, więc sugerowałam się na własnym systemie i tam sprawdzałam co kryje się pod każdym indeksem, choć lista jak się okazało "w praniu" nie przedstawia w dokumentacji kolejności, która zawarta jest w tabeli na stronie.
