### ISSUE TITLE
Program wyłącza się po kliknięciu na towar wybrany z listy

### ISSUE THREAD

**Issue by rocky57** [juliagoda/qfaktury#25]
Po kliknięciu na nazwę towaru w oknie "Wybierz towar z listy" program wyłącza się. W konsoli pokazuje się komunikat: Naruszenie ochrony pamięci.
Sprawdzone na najnowszym Manjaro i Debianie 8.

**Comment by juliagoda** [comment]
Głupie niedopatrzenie z mojej strony. Czy teraz jest w porządku?

**Comment by rocky57** [comment]
Tak, dziękuję za super szybką reakcję! program ma ogromny potencjał - nie wiem czy każdy tak ma ale u mnie pole Nazwa na fakturze zajmuje 60% strony, przez co reszta kolumn na fakturze jest ultra wąska, co powoduje, że kwoty czy nagłówki pozostałych kolumn są podzielone - jedna literka jedna linijka, coś typu:
P
K
W
I
A
6
2.
0
1.
1
Czy planuje Pani dodać export do PDF?
P.

**Comment by juliagoda** [comment]
Program sam automatycznie wykrywa wszystkie dokumenty i tworzy PDF'y na podstawie zapisanych dokumentów do ~/.local/share/data/elinux/pdf-invoices na potrzeby bezpieczeństwa danych. Powinny być dla łatwiejszego wyszukiwania w formacie "dokument-kontrahent-data-numerPliku.pdf" Sprawdź, czy tak jest u Ciebie. Faktycznie nagłówki się rozjeżdżały i okazało się, że to było aż 97% dla pola nazwy. Czy teraz jest OK?
