### ISSUE TITLE
Płatność przelewem

### ISSUE THREAD

**Issue by rocky57** [juliagoda/qfaktury#27]
Przy wyborze płatności przelewem, zawsze pojawia się tekst "zapłacono przelewem", nawet jeśli płatność jest ustawiona na 14 dni na przód. Czy jest możliwość dodania jakiegoś tekstu, np "termin płatności", "sposób zapłaty": przelew?
pozdrawiam

**Comment by juliagoda** [comment]
Witam. Tymczasowo poprawiłam to w testowej wersji, przyjrzę się jeszcze wyglądowi faktury korygującej, która wygląda częściowo nieestetycznie. Nie zwróciłam na to uwagi do tej pory, ponieważ wcześniej czyli przed pomocą byłego "współpracownika" tak się nie rozjeżdżało. Jutro lub w poniedziałek planuję przetestować cały program i poszukać możliwie jak najwięcej błędów. Pozdrawiam.

**Comment by juliagoda** [comment]
Przeniosłam poprawę z wersji testowej z kilkoma innymi poprawkami. Będę starała się wykrywać na bieżąco, testując i szukając błędów. Jeśli coś jest nie tak jak powinno być, to oczywiście czekam na zgłoszenia.

**Comment by rocky57** [comment]
- To tak dodatkowo, co mi przyszło na myśl - po kliknięciu "Zapisz",
faktura jest drukowana - powinna po prostu się zapisać (zwłaszcza, że jest
przycisk drukuj obok).
- Nie korzystam z tych pól, ale na fakturze pola związane z Rabatem, dalej
literka po literce wystepuja w nowym wierszu
- Czy można wyłączyć opcję drukowania kopi (nie moge tego znaleźć)?
- Czy jest szansa dodania buttonu: otworz katalog z fakturami?

dzięki za super szybkie reakcje!

2017-11-13 0:11 GMT+01:00 Jagoda Górska <notifications@github.com>:

**Comment by juliagoda** [comment]
1. Sprawdzę to
2. Dziwne, bo po wczorajszych zmianach i pod zainstalowaniu na nowo w systemie u mnie wygląda to teraz tak, nawet jak wszystkie rubryki są zaznaczone w ustawieniach. Póki co przetestowane na fakturze korygującej i fakturze VAT:

![2017-11-13-125144_1366x768_scrot](https://user-images.githubusercontent.com/24532426/32724481-c3e99292-c871-11e7-81db-ce55494c6652.png)

3. Ustawię dolną granicę na zero w ustawieniach w zakładce "Faktury"
4. To jest bardzo dobry pomysł

**Comment by rocky57** [comment]
po wczorajszych zmianach nie mialem jeszcze mozliwosci przetestowac, zrobię
to dziś wieczorem.

2017-11-13 12:21 GMT+01:00 Piotr Rokosz <piotr.rokosz88@gmail.com>:
