### ISSUE TITLE
Brak automatycznej numeracji faktur

### ISSUE THREAD

**Issue by pavbaranov** [juliagoda/qfaktury#3]
Jak w zgłoszeniu - nic dodać - nic ująć. "Stara" wersja (nie na Qt5) generowała numer nowej faktury.

**Comment by juliagoda** [comment]
Proszę sprawdzić czy dają coś ustawienia, tak jak było w innym wątku

**Comment by pavbaranov** [comment]
Dowolne ustawienia w Ustawienia->Faktury dają ten sam efekt: nowa faktura pojawia się z pierwszym numerem. Tak jak wspominam w innym wątku - problem, prawdopodobnie, polega na jakimś wadliwym generowaniu pliku ~/.config/elinux/qfaktury.conf, albowiem w przypadku, gdy plik ten program "dziedziczył" po wersji 0.6.x wówczas autonumeracja działała. Muszę odszukać stary plik konfiguracyjny, wówczas podam Ci, czego w nowym brakuje. Raczej nie jest to kwestia zmian w *.css, albowiem te dotyczą wyłącznie (chyba) drukowania. 
Mogę jeszcze wygenerować ustawienia przez wersję 0.6.x i tę wersję zaktualizować do 0.7.x i porównać pliki. W takiej sytuacji bowiem autonumeracja działała prawidłowo.

**Comment by juliagoda** [comment]
Byłoby miło, dzięki wielkie

**Comment by pavbaranov** [comment]
Jeszcze tego nie zrobiłem, ale generalnie to problem leży - chyba - gdzieś w treści pliku ~/.config/elinux/qfaktury.conf.
Jak wspomniałem w innym zgłoszeniu ("drukowanie"), pliki ~/.local/share/data/elinux - możemy sobie chyba darować, albowiem te pliki były nienaruszone. Różnica w obu sytuacjach "instalacji" wersji 0.7.x sprowadzała się do tego, że:
- pierwszy raz instalując program robiłem "upgrade" z wersji 0.6.x; wówczas program "przejął" pliki ~/.config/elinux/* oraz ~/.local/share/data/elinux/*; program działał prawidłowo, a automatyczna numeracja istniała,
- drugi raz wykonałem "pierwsze" uruchomienie programu po skasowaniu katalogu ~/.config/elinux/ (drugi katalog istniał i został "przejęty"); start programu odbył się prawidłowo, nastąpiła konfiguracja pliku ~/.config/user.conf (i ten jest prawidłowy) oraz stworzenie pliku ~/.config/qfaktury.conf. Od tego czasu pojawił się problem z "autonumeracją". 
Na mój chłopski rozum, wychodzi zatem na to, że istnieje jakaś różnica pomiędzy plikiem qfaktury.conf generowanym przez obie wersje programu. Nie jest to natomiast raczej błąd w "samym" programie, albowiem gdy ów plik istniał z poprzedniej wersji - program potrafił prowadzić autonumerację. Nie potrafi na pliku wygenerowanym przez samego siebie. Nie widzę żadnych innych plików, które odpowiadałyby za konfigurację programu (pliki w ~/.local to jedyne dane faktur i kontrahentów, plik user.conf to dane użytkownika; innych plików ten program w katalogu lokalnym nie generuje, a pozostałe pliki /czyli w katalogu głównym/ podczas aktualizacji do nowej wersji musiały zostać i tak usunięte i w ich miejsce wpisane nowe).

**Comment by juliagoda** [comment]
Wrzuciłam commit, nie jestem pewna, czy o to właśnie chodzi. Dokonuje autonumeracji, lecz nie korzystając tym razem z pliku konfiguracyjnego, co pobierając do listy numeracje zawarte we wszystkich plikach faktur i wybierając wartość najwyższą. Jeśli w katalogu nie ma żadnych plików, rozpoczyna od 1.  Autonumeracja działa także z dodaniem prefixu, sufixu oraz daty za pomocą ustawień w oknie "Ustawienia". Jeśli usuwa się plik qfaktury.conf, gdy katalog z fakturami nadal istnieje, trzeba ustawić co najmniej poprzednie prefix, sufix, aby autonumeracja objęła uwzględnienie wszystkie istniejące faktury. Oczywiście rozwiązanie jest takie póki co, ponieważ było wdrażane jedynie tego wieczoru i jak mówiłam, dalsze prace zostaną niedługo wznowione.

**Comment by pavbaranov** [comment]
Działa przedziwnie, albowiem w istocie "autonumeruje", jednakże nowy numer faktury generowany jest jako "najwyższy" numer faktury znaleziony w katalogu ~/.local/share/data/elinux/invoices + 1 z pominięciem roku. Innymi słowy jeśli w tym katalogu są (co normalne) faktury z lat ubiegłych, to pierwszy numer faktury w nowym roku nie nosi numeru 1, a jakiś z uwzględnieniem poprzednich lat (np. 168). Ustawienie czegokolwiek na karcie "Faktury/Numeracja" nie ma znaczenia (sufix/prefix nigdy nie stosowałem bo szczerze mówiąc nie widzę sensu tego ustawienia).
Obejście to przenieść poprzednioroczne faktury do jakichś katalogów archiwum. Wówczas jednak - dostęp do tych faktur jest wyłącznie po ich ponownym przeniesieniu do ww. katalogu z fakturami.

**Comment by juliagoda** [comment]
Teraz obejmuje tylko faktury z aktualnego roku. Jakby dalej coś było nie tak to daj znać, ponieważ raczej kiepsko znam się na fakturach

**Comment by pavbaranov** [comment]
Działa. Do zamknięcia. Thx.
