### ISSUE TITLE
zbyt małe pole na logo firmy 

### ISSUE THREAD

**Issue by etammable** [juliagoda/qfaktury#33]
Witam. Myślę, że pole na logo firmy powinno być zwiększone, bo obecne 100x100 jest często bezużyteczne dla osób które mają logo na "bazie" prostokątu . Ja dla własnych potrzeb zmieniłem sobie na 200x81 (taka akurat miałem grafikę), ale gdyby domyślnie zmienić na 200(width) i 200(height) byłoby znacznie lepiej. * 

namiary miejsca gdzie się to zmienia: 
https://github.com/juliagoda/qfaktury/blob/master/src/Invoice.cpp  wiersz 2035

"<img src=\"" + logo + "\" width=\"200\" " + " height=\"200\" alt=\"Logo firmy\" />";

pozdrawiam. 
ps. 
Można też w wierszu 2029 ( invStrList += "<td width=\"60%\" align=\"center\" valign=\"bottom\">";)
zmienić align na "left" zamiast "center", ale to już kwestia smaku estetycznego :)

*zmieniłem po namyśle propozycje zmiany z 200x100 na 200x200, bo w takim kwadracie się już każdy zmieści.

**Comment by juliagoda** [comment]
Nie ma sprawy, w poniedziałek się tym zajmę

**Comment by juliagoda** [comment]
Zmienione na 200 X 200
