### ISSUE TITLE
zaokrąglanie Vat 

### ISSUE THREAD

**Issue by etammable** [juliagoda/qfaktury#37]
Witam. Chciałem poinformować, że program źle wylicza Vat, tzn zaokragla go w dół lub góre, takie zaokrąglanie jest niedopuszczalne w księgowości w Polsce. np. wystawiając fakture na sumę brutto 30zł na towar opodatkowany stawka vat 8% na fakturze wyliczona jest poprawna kwota netto (27,78), ale kwota vat zamiast 2,22zł wylicza na 3zł 

Niestety nie wiem w którym miejscu kodu to poprawić. 

Pozdrawiam

**Comment by juliagoda** [comment]
Witam. Czy teraz jest lepiej, czy nadal są jakieś problemy z tym związane?

**Comment by etammable** [comment]
Jutro sprawdzę, trzeba iść już spać, dobranoc :)

**Comment by juliagoda** [comment]
:D

**Comment by etammable** [comment]
Jeżeli chodzi o wyliczanie vatu to problem nadal występuje

![screenshot from 2018-01-13 21-27-32](https://user-images.githubusercontent.com/33988835/34909820-e20d18e0-f8a8-11e7-900c-b376449100be.png)

**Comment by sirlucjan** [comment]
Kompilowałeś najnowszy commit czy wersję źródłową pobraną stąd: https://github.com/juliagoda/qfaktury/releases?

**Comment by juliagoda** [comment]
A to mój zrzut po usunięciu katalogu głównego oraz plików konfiguracyjnych:

![zrzut](https://user-images.githubusercontent.com/24532426/34916614-65dcedfc-f93b-11e7-8ce3-6dce347b1930.png)

**Comment by etammable** [comment]
kompilowałem tę wersję z instrukcji instalacji:
 
```
Instalacja

Wykonujemy pobranie katalogu z plikami w wybranej przez siebie ścieżce i wpisujemy polecenia:

git clone -b testing https://github.com/juliagoda/qfaktury.git
cd qfaktury
mkdir zbudowane
cd zbudowane
cmake ..
make
sudo make install

```
`git clone -b testing https://github.com/juliagoda/qfaktury.git` --to chyba do poprawy?

**Comment by juliagoda** [comment]
tak, do poprawy. Już poprawione. Podczas pull request z testowej wersji do master musiały się przenieść też treści README.
