### ISSUE TITLE
problem z instalacją na ubuntu i linuxmint, błędy przy make

### ISSUE THREAD

**Issue by etammable** [juliagoda/qfaktury#38]
Witam. Nie wiem czy to właściwe miejsce to zgłaszania tego rodzaju problemów, ale wyskakują następujace błedy przy instalacji na poleceniu make:

`In file included from /home/cynamon/qfaktury/src/MainWindow.cpp:16:0:
/home/cynamon/qfaktury/src/Setting.h: In member function ‘void Setting::settReadBackup(QString)’:
/home/cynamon/qfaktury/src/Setting.h:88:30: error: ‘class QString’ has no member named ‘back’
           else if (settValue.back() == 'h') { backupEveryHour->setChecked(true); settValue.chop(1); howManyHours->setValue(settValue.toInt()); }
                              ^~~~
In file included from /home/cynamon/qfaktury/src/MainWindow.cpp:16:0:
/home/cynamon/qfaktury/src/Setting.h:89:30: error: ‘class QString’ has no member named ‘back’
           else if (settValue.back() == 'm') { backupEveryMin->setChecked(true); settValue.chop(1); howManyMin->setValue(settValue.toInt()); }
                              ^~~~
/home/cynamon/qfaktury/src/MainWindow.cpp: In member function ‘void MainWindow::init()’:
/home/cynamon/qfaktury/src/MainWindow.cpp:370:54: error: ‘class QString’ has no member named ‘back’
       if (sett().value("backup_interval").toString().back() == 'h') {
                                                      ^~~~
/home/cynamon/qfaktury/src/MainWindow.cpp:377:61: error: ‘class QString’ has no member named ‘back’
       } else if (sett().value("backup_interval").toString().back() == 'm') {
                                                             ^~~~
/home/cynamon/qfaktury/src/MainWindow.cpp: In member function ‘void MainWindow::intervalBackup()’:
/home/cynamon/qfaktury/src/MainWindow.cpp:3780:69: error: ‘class QString’ has no member named ‘back’
   QChar periodTimeSymb = sett().value("backup_interval").toString().back();
                                                                     ^~~~
CMakeFiles/qfaktury.dir/build.make:515: polecenia dla obiektu 'CMakeFiles/qfaktury.dir/src/MainWindow.cpp.o' nie powiodły się
make[2]: *** [CMakeFiles/qfaktury.dir/src/MainWindow.cpp.o] Błąd 1
CMakeFiles/Makefile2:67: polecenia dla obiektu 'CMakeFiles/qfaktury.dir/all' nie powiodły się
make[1]: *** [CMakeFiles/qfaktury.dir/all] Błąd 2
Makefile:129: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2
`
Raczej mało prawdopodobne bym niemiał jakiejś zależnośc, bo zainstalowałem któryś z forków z listopada/grudnia bez żadnego kłopotu. Pozd

ps. Jeżeli to niewłaściwe miejsce do tego rodzaju postu to proszę go usunąć

**Comment by juliagoda** [comment]
Nie, jest ok. Jakikolwiek błąd związany z programem jest w porządku. Będę musiała chyba zrobić mały wywiad, bo na Arch Linux ten błąd (póki co) nie występuje i pomyśleć co dalej

**Comment by sirlucjan** [comment]
Mógłbyś podać wersje systemów na których to kompilujesz oraz wersje wszystkich zależności wymienionych w pliku readme.md, łącznie z wersją biblioteki Qt? Podejrzewam, że to będzie kluczowe dla rozwiązania problemu. Skompilowałem właśnie najnowszy commit i nie ma najmniejszego problemu.

```
==> Sprzątanie instalacji...
  -> Usuwanie libtool plików...
  -> Usuwanie niechcianych plików...
  -> Usuwanie statycznych plików bibliotek
  -> Wyrzucanie niepotrzebnych symboli z plików binarnych i bibliotek
  -> Kompresowanie stron man oraz info...
==> Sprawdzanie problemów pakowania...
==> Tworzenie pakietu "qfaktury-qt5-git"...
  -> Generowanie pliku .PKGINFO...
  -> Generowanie pliku .BUILDINFO...
  -> Generowanie pliku .MTREE...
  -> Kompresowanie pakietu...
==> Podpisywanie pakietu...
  -> Utworzono plik podpisu /home/lucjan/Pobrane/roboczy-2/qfaktury-qt5-git/qfaktury-qt5-git-0.7.1.125.gcebb6a4-1-x86_64.pkg.tar.xz.sig.
==> Opuszczanie środowiska fakeroot.
==> Ukończono tworzenie: qfaktury-qt5-git 0.7.1.125.gcebb6a4-1 (czw, 11 sty 2018, 13:45:37 CET)
```

**Comment by sirlucjan** [comment]
W ramach sprawdzenia, skompilowałem także wersję bazującą na KF5. Działa bez najmniejszego problemu. 

```
==> Sprzątanie instalacji...
  -> Usuwanie libtool plików...
  -> Usuwanie niechcianych plików...
  -> Usuwanie statycznych plików bibliotek
  -> Wyrzucanie niepotrzebnych symboli z plików binarnych i bibliotek
  -> Kompresowanie stron man oraz info...
==> Sprawdzanie problemów pakowania...
==> Tworzenie pakietu "qfaktury-kf5-git"...
  -> Generowanie pliku .PKGINFO...
  -> Generowanie pliku .BUILDINFO...
  -> Generowanie pliku .MTREE...
  -> Kompresowanie pakietu...
==> Podpisywanie pakietu...
  -> Utworzono plik podpisu /home/lucjan/Pobrane/roboczy-2/qfaktury-kf5-git/qfaktury-kf5-git-0.7.0.16.g58de9ca-1-x86_64.pkg.tar.xz.sig.
==> Opuszczanie środowiska fakeroot.
==> Ukończono tworzenie: qfaktury-kf5-git 0.7.0.16.g58de9ca-1 (czw, 11 sty 2018, 13:50:31 CET)
```
Podejrzewam, że masz jakąś starszą wersję biblioteki lub czegoś nie ma - jeśli kompilujesz z najnowszego commitu z gałęzi master, to problem **prawdopodobnie** występuje po stronie Twojego systemu - w Arch Linux zbudowałem to bez najmniejszego problemu, jeśli będziesz chciał, mogę wrzucić pełne logi z kompilowania.

**Comment by etammable** [comment]
> Podejrzewam, że masz jakąś starszą wersję biblioteki lub czegoś nie ma

Prawdopodobnie. Próbowałem instalacji na linuxmint 18.03 i lubuntu 17.10 i na obu pojawiają się takie błędy jak wyżej, chociaż na komputerze z lubuntu zainstalowałem bez problemu w końcu listopada - od tego czasu zmieniły się wymagania co do wersji bibliotek itd? W obu dystrybucjach których teraz używam biblioteki defaultowo są w starszych wersjach i nazwy pakietów troche róznią się od tych o których piszecie. Próbowałem instalować biblioteki z wersji testowej ubuntu 18.4, ale to nie najlepiej wychodzi, jednym takim upgradem nieźle sobie namieszałem :) pozdrawiam 

ps. W weekend jeszcze powalcze z qfaktury, napiszę też wersje bibliotek itd.

**Comment by juliagoda** [comment]
Jak będziesz działał to spróbuj dodać zależności wymienione w README. Przy okazji będę miała pewność, że program na innych dystrybucjach działa/nie działa

**Comment by sirlucjan** [comment]
Od listopada mogło się zmienić bardzo dużo - w tamtym czasie w Arch "obowiązywała" biblioteka Qt 5.9, aktualnie mamy 5.10 - która wniosła całkiem sporo zmian. Podobnie może być u Ciebie - wymień listę zależności i wersje jakie masz, my zrobimy to samo z paczkami w Arch. Będzie jakiś punkt odniesienia.

**Comment by sirlucjan** [comment]
Radziłbym nie mieszać bibliotek pomiędzy wydaniami Ubuntu - możesz sprawić sobie nieliche problemy. W wolnej chwili trzeba będzie porównać nazwy pakietów w readme i nieco je zaktualizować.

**Comment by etammable** [comment]
Witam. Próbowałem jeszcze raz instalacji, tym razem konserwatywnie bez instalacji pakietów z wyższych/testowych wydań ubuntu i szczegółowym uwzględnieniem wymagań z pliku readme.md. 

W wersji 16.04 ubuntu i jego pochodnych nie ma takiej paczki jak qt5-webengine, ona pojawia się dopiero 18.04 i przy cmake .. wyskakuje bład:




> cmake ..
> -- /usr/share/ECM/modules/;/usr/share/ECM/find-modules/;/usr/share/ECM/kde-modules/;/home/bbb/qfaktury/cmake/modules
> CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
>   Could not find a package configuration file provided by
>   "Qt5WebEngineWidgets" with any of the following names:
> 
>     Qt5WebEngineWidgetsConfig.cmake
>     qt5webenginewidgets-config.cmake
> 
>   Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
>   or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
>   files.  If "Qt5WebEngineWidgets" provides a separate development package or
>   SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:113 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/bbb/qfaktury/zbudowane/CMakeFiles/CMakeOutput.log".

Nie mogę nigdzie znaleźć tej paczki pasującej do 16.04, zainstalowałem nawet coś takiego, ale to nie rozwiązało problemu https://wiki.qt.io/Install_Qt_5_on_Ubuntu



W ubuntu 16.04 nie ma też cmake, quazip w wymaganych wersjach, ale znalazłem jakieś prywatne ppa gdzie one były. 

Ps. zainstalowałem na wirtalnej maszynie ubuntu 18.04, na tej wersji cmake przechodzi, ale na make wyskakują podobne błędy jak na początku tego wątku. W tej wersji wszystkie wymagane pakiety są w wymaganych wersjach w repozytoriach.  https://packages.ubuntu.com/

Pozdrawiam

**Comment by sirlucjan** [comment]
Jaką wersję biblioteki Qt5 posiadasz? U mnie na Qt 5.10 buduje bez problemu.

**Comment by juliagoda** [comment]
qt5-webengine wygląda na Arch Linux i pochodnych. Zjedź trochę niżej, gdzie są zależności opisane na Ubuntu. Będę musiała nanieść poprawkę w README na samej górze przy wytłuszczonych zależnościach i napisz jak byś mógł, czy coś się zmieniło i co się zmieniło.

**Comment by etammable** [comment]
qt5 - 5.5.1

**Comment by etammable** [comment]
>Zjedź trochę niżej, gdzie są zależności opisane na Ubuntu

Masz na myśli to? 

> sudo apt-get install -y language-pack-en-base
sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.1 php7.1-common zlib1g-dev zlib1g cmake gksu qtbase5-dev qtwebengine5-dev libquazip-qt5-dev extra-cmake-modules

Jeżeli tak to wszystko to zrobiłem. to dodatkowe ppa jest nawet niepotrzebne, bo repozytoriach obecnie jest wyższa wersja php

**Comment by juliagoda** [comment]
dobrze to odnośnie PHP wiedzieć, w takim razie to po prostu wycofam

**Comment by sirlucjan** [comment]
Masz bardzo starą wersję Qt - podejrzewam, że moglibyśmy spędzić godziny na szukaniu rozwiązania i nic by to nie dało.

**Comment by sirlucjan** [comment]
Ostatnie poprawki Qt 5.5.1 otrzymało w październiku 2015 roku:

http://download.qt.io/archive/qt/5.5/5.5.1/

Biorąc pod uwagę, że kod projektu jest dostosowywany do najnowszych bibliotek - szanse na obejście problemu są zerowe.

**Comment by juliagoda** [comment]
Z tego co mi się przypomniało, to raz ten sam błąd co twój mi wyskoczył i pewnie po aktualizacji. Była taka sytuacja, że dnia poprzedniego kod działał a następnego dnia nagle się nie kompilował, gdy chciałam pracować na IDE, pokazując dokładnie te same błędy w tym samym miejscu i prawdopodobnie po naniesieniu poprawek teraz u Ciebie może nie działać, jako że masz nie 5.10.0 a 5.5.1.

**Comment by etammable** [comment]
W wymaganiach napisaliście 

> biblioteka Qt w wersji wyższej lub równej 5.0.0

spróbuję poszukać wyższej wersji :)

W ubuntu 18.04 wersja jest 5.9.3

**Comment by sirlucjan** [comment]
Dodatkowo nie masz szans mieć qt5-webengine w wersji 5.5:

http://doc.qt.io/Qt-5/whatsnew56.html

Moduł ten został dodany do wersji 5.6 i co za tym idzie - w starszych wersjach tego nie uświadczysz.

Myślę, że:

```
set(QT_MIN_VERSION "5.10.0")
```
rozwiąże problem. Jeśli nie znajdzie odpowiedniej wersji w systemie, nie rozpocznie kompilacji.

**Comment by juliagoda** [comment]
> W wymaganiach napisaliście biblioteka Qt w wersji wyższej lub równej 5.0.0

To w takim razie się to też zmieni, faktycznie tego zapomniałam w późniejszym czasie poprawić

**Comment by etammable** [comment]
Jak będziecie "gonić" za nowościami to z ubuntu zawsze będzie problem, bo oni zawsze są trochę do tyłu. Fajnie, że podjedliście się rozwoju tego programu, ja od kilku lat używałem jego martwej wersji i przypadkowo trafiłem do Was. Pozdrawiam

**Comment by sirlucjan** [comment]
Ciężko rozwijać program pod wiele systemów mając ograniczoną siłę przerobową. Brakuje ot choćby beta-testerów na systemy bazujące na Debianie/Ubuntu czy rpm.

**Comment by juliagoda** [comment]
To niestety prawda, tym bardziej że "sirlucjan" nic nie musi i to, że pomógł mi choćby na tym wątku to jest jego własna wola i czy to, czy będzie miał akurat czas mi coś sprawdzić czy przetestować też, bo ma dużo własnych spraw na głowie i własną działalność dla Arch Linux. Prawie wszystko co się na tym programie dzieje, zależy tylko ode mnie. No cóż, staram się.

**Comment by etammable** [comment]
Jakby dało się zainstalować program w paczkach deb albo rpm napewno jacyś testerzy by się znaleźli, bo wielu ludzi już sama konieczność kompilacji odrzuca. Jak mi się uda to zrobię paczkę deb, dla tej martwej wersji zrobiłem dla własnej wygody, więc może się uda dla waszej :)

**Comment by juliagoda** [comment]
Jakby się dało to byłoby fajnie, ale też oczywiście nic na siłę

**Comment by sirlucjan** [comment]
Wiesz, żeby robić paczki deb i rpm potrzebowalibyśmy solidny komputer z kilkoma virtualnymi maszynami - tam Ubuntu, Debian, Fedora, openSUSE - wszystko kompilować w clean chroocie bo paczek produkcyjnych inaczej robić nie można. Do tego jakiś hosting, domena - w końcu gdzieś trzeba trzymać paczki, żeby je trzymać - oczywiście na początek sourceforge by wystarczyło, ale punkt pierwszy jest już ciężki do ogarnięcia dla małego a w zasadzie "półtorej osobowego" zespołu - mój jedyny wkład w rozwój programu to testy na platformie Arch Linux.

**Comment by etammable** [comment]
Udało mi się skompilować przy Qt 5.10.0 bez błędów (był jakiś jeden warning) użyłem tego ppa może komuś się przyda  `sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial`

ale!
pomimo, że po instalacji pojawiła się ikonka w menu, jak się na nią kliknie to chwile mieli i nie uruchamia się, a jak uruchamiam z terminala to wyskakuje 

> qfaktury: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory

jak kliknę na qfaktury w katalogu zbudowane to program się uruchamia normalnie.

ps. dodatkowe ppa które użyłem przy instalacji 

cmake >>  `sudo add-apt-repository ppa:nschloe/cmake-nightly`
quazip >>   `sudo add-apt-repository ppa:aroth/ppa`

**Comment by sirlucjan** [comment]
Niestety - nie mogę potwierdzić błędu. Program uruchamia się z menu bez problemu, z terminala nie zwraca żadnych błędów.

Wersja Qt5:

https://s10.postimg.org/cp72jsni1/2018-01-14-135827_1366x768_scrot.png

Wersja KF5:

https://s10.postimg.org/k56c5mds9/2018-01-14-135952_1366x768_scrot.png

Pokaż co zwróci Ci polecenie:

```
apt-cache policy libqt5xml5
```
Mam nadzieję, że polecenie to dalej w Debianowatych obowiązuje :D 

Pokaż też wynik polecenia:

```
locate libQt5Xml.so
```
Jeśli nie masz tego u siebie, zainstaluj program mlocate i wykonaj polecenie z prawami roota:

```
updatedb
```
Powinno zadziałać.

**Comment by etammable** [comment]
```
libqt5xml5:
  Installed: (none)
  Candidate: 5.5.1+dfsg-16ubuntu7.5
  Version table:
     5.5.1+dfsg-16ubuntu7.5 500
        500 http://ftp.icm.edu.pl/pub/Linux/ubuntu xenial-updates/main amd64 Packages
     5.5.1+dfsg-16ubuntu7 500
        500 http://ftp.icm.edu.pl/pub/Linux/ubuntu xenial/main amd64 Packages

```
taki rezultat dostaje nawet jak mam zainstalowane pełne qt 5.10.0 z tego ppa ppa:beineri/opt-qt-5.10.0-xenial (facet który zrobił te paczki jakoś dziwnie sobie je ponazywał, a przynajmniej inaczej niż tego potrzebuje ubuntu). Zainstalowałem też na próbę całe qt 5.10.0 z instalatora []https://howto-ubuntunew.blogspot.com/2017/12/how-to-install-qt-5100-released-on.html, ale ubuntu tej instalacji w ogóle "nie widzi".  Dodatkowo jak usunę paczkę libqt5xml5 5.5.1+dfsg-16ubuntu7.5 to odinstalowuje mi qjacktl (takie narzędzie do konfiguracji jack). 

Myślę, że te problemy wynikają z rożnych filozofii rozwojowych dystrybucji  Arch i ubuntu, pierwsza goni za nowością i eksperymentem, a druga za stabilnością i user friendly.  Pozd

**Comment by sirlucjan** [comment]
```
libqt5xml5:
  Installed: (none)
```
Jak rozumiem, paczka ta nie jest zainstalowana, natomiast w niej znajduje się biblioteka, której program potrzebuje:

```
/usr/lib/x86_64-linux-gnu/libQt5Xml.so.5
```
Pokaż wynik tego drugiego polecenia, o który Cię prosiłem. U mnie zwraca następujący wynik:

```
locate libQt5Xml.so
/usr/lib/libQt5Xml.so
/usr/lib/libQt5Xml.so.5
/usr/lib/libQt5Xml.so.5.10
/usr/lib/libQt5Xml.so.5.10.0
```

Ubuntu jest dystrybucją wydawniczą, Arch ciągłą - to jest największa różnica. Dystrybucje ciągłe z samego założenia mają najnowsze wersje pakietów. Natomiast Ubuntu, szczególnie wersje LTS po czasie są bardzo mocno w plecy z aktualnością - czego skutek możesz obserwować u siebie. W idealnym świecie program powinien mieć różne gałęzie przeznaczone do poszczególnych wersji systemu - wtedy wszystko u każdego by działało. Niestety, taki rozwój sytuacji jest niemożliwy - barierami są zasoby ludzkie, pieniężne, czasowe - aby rozwijać program w ten sposób, aplikacja musi być w jakiś sposób finansowana bądź rozwijana przez cały sztab pracowników tudzież społeczność. Niestety, aktualnie program jest robiony tylko i wyłącznie przez jedną osobę - mającą na swojej głowie także inne obowiązki, więc dostosowanie do każdej istniejącej dystrybucji w każdej istniejącej wersji jest zwyczajnie niewykonywalne.

Ubuntu z pewnością jest dystrybucją user-friendly (z definicji) jednakże jako jej były użytkownik nie zapędzałbym się z nazwaniem jej stabilną. Problemy przy aktualizacji do wyższej wersji to chleb powszedni (wystarczy przeszukać polskie fora), często marnej jakości repozytoria PPA co nie świadczy
dobrze o społeczności. Nie ma distra idealnego, każde ma swoje wady (tak, Arch także trochę ich ma) ale trzeba się kierować bilansem zysków i strat, który rzecz jasna dla każdego użytkownika jest inny. 

Ubuntu 16.04 posiada Qt 5 w niewspieranej już wersji, co ciężko nazwać plusem dystrybucji szczycącej się mianem "long time support". 

Jak podasz wynik drugiej komendy, o którą Cię prosiłem, będziemy kombinować co dalej.

**Comment by etammable** [comment]
Przy zainstalowanym pełnym qt 5.10.0 z ppa o którym wcześniej mówiłem

locate libQt5Xml.so


/opt/qt510/lib/libQt5Xml.so
/opt/qt510/lib/libQt5Xml.so.5
/opt/qt510/lib/libQt5Xml.so.5.10
/opt/qt510/lib/libQt5Xml.so.5.10.0

polecenie updatedb się wykonuje, ale nie daje żadnych informacji w terminalu

**Comment by sirlucjan** [comment]
Musisz zrobić dowiązanie symboliczne i problem zniknie. Masz bibliotekę w innym miejscu, niż oczekuje tego program - w tym wypadku zewnętrzna biblioteka Qt całkiem słusznie ląduje w katalogu /opt - jedyne co musisz zrobić, to stworzyć dowiązanie symboliczne tak, by program szukał biblioteki tam, gdzie trzeba. 

Polecenie updatedb nie daje zwrotnej informacji.

**Comment by etammable** [comment]
`Polecenie updatedb nie daje zwrotnej informacji.`
Nie 
Z tym dowiązaniem symbolicznym to muszę najpierw obczaić jak sie to robi . Rozumiem że chodzi o to by w usr/lib był plik przekierowujący do /opt/qt510/lib ? :)

**Comment by sirlucjan** [comment]
Polecenie updatedb nie daje zwrotnej informacji. - to było stwierdzenie i informacja, nie pytanie.

Tak, dowiązanie musi być utworzone tam, gdzie domyślnie znajduje się Qt.

Jak zrobić zobacz tutaj: https://askubuntu.com/questions/56339/how-to-create-a-soft-or-symbolic-link

Leciwy poradnik ale dalej na czasie.

**Comment by etammable** [comment]
dzięki. Dałem symboliczny dla całego katalogu i wszystko działa jak trzeba `sudo ln -s /opt/qt510/lib/* /usr/lib` 

Ps. 
Spiszę te moje boje z instalacją qfaktury na ubuntu w uporządkowanej formie by oszczędzić innym roboty. Pozdrawiam

**Comment by etammable** [comment]
Radość była przedwczesna :) 
Jak kompiluję ten commit `git clone -b testing https://github.com/juliagoda/qfaktury.git` to wszystko przechodzi.

![screenshot from 2018-01-15 00-37-03](https://user-images.githubusercontent.com/33988835/34922185-afdd7f06-f98c-11e7-8000-39f34ab6664b.png)

`

!ale gdy przy takich samych ustawieniach (zainstalowanych paczkach) staram się skompilować ten właściwy `git clone https://github.com/juliagoda/qfaktury.git` to otrzymuję: 

![screenshot from 2018-01-15 00-37-46](https://user-images.githubusercontent.com/33988835/34922186-c673a83a-f98c-11e7-8101-ec296bdaeef7.png)


Nie wiem już o co chodzi, czy jakaś paczka znów jest w zbyt niskiej wersji? :( Mam nadzieję, że nie irytuję Was moją pisaniną tutaj. Pozdrawiam

**Comment by sirlucjan** [comment]
Narobił się tutaj mały sajgon - wcześniej pisałeś z Ubuntu a teraz z Linux Mint? Jeśli tak, to jakiej wersji? Wpis o gałęzi testowej wkradł się do README przez pomyłkę - z tej gałęzi nie należy korzystać, jak sama nazwa wskazuje, to poligon doświadczalny i zabawka dla ewentualnych testerów. 

Jeśli zgłaszasz błąd, wypadałoby wspomnieć o platformie na jakiej działasz - to jest bardzo pomocne. Tak jak poprzednio - błędu potwierdzić nie mogę, zbudowałem najnowszy commit bez problemu, załączam pełny log budowy:

http://wklej.org/id/3344601/

Tak jak ostatnio, proszę o podanie wersji poszczególnych zależności.

**Comment by etammable** [comment]
Witam. Pisałem przecież o tym, że instaluje na linux mint 18.03 to niczym nie różni się od ubuntu 16.04, te same repozytoria itd, tylko srodowisko graficzne inne. Wszystkie zależności zgodne z wytycznymi autorki.

**Comment by juliagoda** [comment]
A czy możesz teraz spróbować? Usunęłam tę linijkę, tak samo jak kiedyś z gałęzi KF5. Ta linijka i tak niewiele robi, bo wyświetla jedynie zwrotną informację o progresie. Faktycznie mogło nie ruszyć, bo wczoraj dodałam nowe dyrektywy do CMakeLists, które bardziej restrykcyjnie sprawdzają kompilowany kod, dlatego ruszyło na testowej wersji, ale nie już na master. Odezwały się kwestie bezpieczeństwa

**Comment by sirlucjan** [comment]
Mam następujące wersje:

```
core/zlib 1:1.2.11-2 
    Compression library implementing the deflate compression method found in gzip and PKZIP
extra/gksu 2.0.2-6                                                                                                                                                                              
    A graphical frontend for su
extra/php 7.2.1-1
    A general-purpose scripting language that is especially suited to web development
extra/cmake 3.10.1-2
    A cross-platform open-source make system
community/quazip 0.7.3-3
    C++ wrapper for the Gilles Vollant's ZIP/UNZIP C package
extra/qt5-base 5.10.0-2 (qt qt5)
    A cross-platform application and UI framework
extra/qt5-webengine 5.10.0-2 (qt qt5)
    Provides support for web applications using the Chromium browser project
extra/extra-cmake-modules 5.41.0-1
    Extra modules and scripts for CMake
```

O Mincie wspominałeś na początku, jednakże następne błędy dotyczyły Ubuntu - tam zainstalowałeś nowe wersje Qt5 i kompilowanie ruszyło, po utworzeniu dowiązań program zaczął działać. Na Linux Mint powtórzyłeś dokładnie te same kroki?

**Comment by etammable** [comment]
Na linux mint zrobilem dokładnie "te same kroki". Wieczorem przetestuje jeszcze raz, bo w pracy jestem, mam tu ubuntu 17.10 , ale kiepski internet i 1gb qt bedzie sie ściągał godzine. Mam nadzieje, że wasz nie dreczę tymi problemami? :) ps. Sajgon w wątku,  ale kilka rzeczy udało się uporządkować. Pozd

**Comment by juliagoda** [comment]
> Mam nadzieje, że wasz nie dręczę tymi problemami?

No trudno, jak się podjęliśmy pracy nad prowadzeniem programu, to do czegoś zobowiązuje. Nie jest łatwo wszystko razem pogodzić, bo i akurat sesja jest na karku, ale stać w miejscu z samorozwojem w tej branży też nie wypada.

**Comment by etammable** [comment]
Na linux mint zrobilem dokładnie "te same kroki". Wieczorem przetestuje jeszcze raz, bo w pracy jestem, mam tu ubuntu 17.10 , ale kiepski internet i 1gb qt bedzie sie ściągał godzine. Mam nadzieje, że wasz nie dreczę tymi problemami? :) ps. Sajgon w wątku,  ale kilka rzeczy udało się uporządkować. Pozd

**Comment by etammable** [comment]
Kompilacja działa jak należy :)
![screenshot from 2018-01-15 19-07-49](https://user-images.githubusercontent.com/33988835/34956458-76e6e726-fa29-11e7-9d10-1e8b24084021.png)

Jak wcześniej mówiłem, napisze taki "mini przewodnik" instalacji na ubuntu/linuxmint i prześlę go na maila juliagoda, żeby nikt już nie zawracał Wam takimi rzeczami głowy. 

Dziękuje za cierpliwość i
Pozdrawiam
