### ISSUE TITLE
Program nie dodaje kontrahenta do wydruku oraz nie zapamiętuje go

### ISSUE THREAD

**Issue by pavbaranov** [juliagoda/qfaktury#4]
Wersje rc3 i rc4 nie są w stanie wygenerować prawidłowego wydruku. Dodają do niego wszystkie informacje z wyjątkiem danych kontrahentów. 

Po ponownym otwarciu programu i zapisanej właśnie faktury - dane kontrahenta są wadliwe.
Prawdopodobnie odpowiada za to wadliwie generowany plik *.xml danej faktury, albowiem pole <buyer ma następującą postać:
<buyer name="PRAWIDŁOWO" tic="PRAWIDŁOWO" website=">" account="------" email="-" phone="-" street="PRAWIDŁOWO" city="PRAWIDŁOWO"/>
Zdaje się, że problem powoduje znak ">" po słowie website, który sam się generuje.

EDIT:
Ostatecznie - wiem o co chodzi i już zapamiętuje i drukuje prawidłowo.
Z jakiejś przyczyny program przy pierwszym starcie ustawia "puste" pola do wydruku jako pola kontrahenta. Zatem błąd chyba leży w innym miejscu (jeśli to błąd, bo można dać również "zajawkę", że należy te pola ustawić i... wyjść z programu i ponownie do niego wejść, albowiem inaczej nie wygeneruje prawidłowego wydruku.

**Comment by juliagoda** [comment]
Tak, w ustawieniach według własnego uznania się zaznacza pola itd. W najbliższym czasie przejrzę jeszcze dokładnie, bo kod jest cały czas poprawiany i dodatkowo będzie przetłumaczony itd. Ostatnio działam mniej bo pojawiła się sesja i jest trochę spraw innych na głowie, więc proszę o odrobinę wyrozumiałości, ponieważ wszystko będzie nadal kontynuowane.

**Comment by pavbaranov** [comment]
Po pierwsze - udanej sesji.
Po drugie - wszystkie 3 ostatnie zgłoszenia są wynikiem tylko i wyłącznie jednej "zmiany". Z pewnych przyczyn skasowałem pliki w katalogu ~/.config/elinux/. Są tam dwa. Przy starcie qfaktur, program potraktował to jak "pierwszy start", zatem pliki zostały utworzone. Na pewno nic nie ma do rzeczy plik user.conf, bo to są dane użytkownika. W wolnej chwili sprawdzę czym różni się plik qfaktury.conf utworzony w wersji 0.6 i 0.7.
Zgłoszenie do zamknięcia, bo po poustawianiu danych kontrahenta do druku - działa prawidłowo. Przydałoby się po prostu dać jakąś zmianę w zakresie ustawiania owego "pierwszego" startu, która wskazywałaby na konieczność ustawienia karty Ustawienia -> Wydruki, albowiem tutaj (sprawdzę) pojawia się jakaś niekonsekwencja i dane użytkownika na fakturze są bodaj wszystkie zaznaczone domyślnie do wydruku, a wszystkie dane kontrahenta są zaznaczone jako niedrukowane. Sprawdzę to jeszcze. Tak, czy inaczej - temat raczej do "Pull requests", a nie do "Issue".
Jeśli chodzi o tłumaczenie - mogę zrobić na angielski. Pytanie jedynie, czy jest sens, ale o tym jeszcze pogadamy po sesji.

**Comment by juliagoda** [comment]
Dodałam na wszelki możliwość dla warunku, jeśli program został uruchomiony po raz pierwszy a nie ma katalogu elinux w ścieżce ~/.local/share/data/elinux oraz oraz/lub jego podkatalogów, to ma je znów zbudować, korzystając z istniejącej już funkcji.

Przejrzę niedługo jeszcze ustawienia domyślne i zajmę się w takim razie zaznaczaniem opcji, aby zamiast użytkownik zaznaczał, odznaczał czego nie chce na polu faktury. Nie wiem tylko i to od pewnego czasu, czy zrobić to samo dla opcji możliwości edycji faktur oraz zmiany symboli w lewym górnym rogu. Raz myślałam, że zablokowałam przypadkowo wszystkie okna dla faktur, a okazało się, że opcja edycji nie była zaznaczona w ustawieniach. 

Jeśli chodzi o języki obce, to nie robiłam tego od razu ze względu na zmiany kodu, ponieważ QTranslator przechodzi przez cały kod w projekcie i "zbiera" wszystkie wartości char, które znajdują się w obrębie trUtf8, a które mogą zostać podczas poprawy kodu zmienione czy usunięte czy dodane bardziej rozległe opisy.

Fakt wszystkie zgłoszenia dotyczyły jednego, jednak niepisana zasada mówi o udzieleniu odpowiedzi pod każdym osobnym wątkiem i dlatego przed udzieleniem odpowiedzi pod każdą z nich, zasięgnęłam porady w tej sytuacji osoby, która korzysta o wiele więcej i dłużej z Github'a niż ja.

Dzięki za trzymane kciuki na sesję, gdyż będą 4 egzaminy za tydzień i kilka dni. Chociaż o tyle nieobecność nie poszła na marne ze względu na zdany certyfikat z html, css i javascript. Nie będę chwilowo tak dużo pracować jak do tej pory, ale zaglądam codziennie i sprawdzam, czy wszystko jest w porządku.

**Comment by pavbaranov** [comment]
Hmmm.... opisywana tu "przypadłość" raczej nie powinna mieć wiele wspólnego z katalogiem ~/.local/share/date/elinux, albowiem ten katalog u mnie nie był naruszony (cały czas istniał). Nie wymagał odbudowania. 
O reszcie w takim razie - przy "automatycznej numeracji" :)

**Comment by juliagoda** [comment]
Ja rozumiem że tego u ciebie nie było, ale wykryłam że po pierwszym uruchomieniu programu w przypadku jeśli nie było katalogu elinux i jego podkatalogów, po ponownym uruchomieniu nie zapisywały się dane towarów, kontrahentów i faktur, a że ponowne uruchomienie już nie było pierwszym uruchomieniem, działało na innych zasadach, które było poprawniejsze. Dlatego dodałam tę funkcję.
