### ISSUE TITLE
Niepoprawna instrukcja instalacji zależności dla linuxmint i ubuntu

### ISSUE THREAD

**Issue by etammable** [juliagoda/qfaktury#41]
Witam jeszcze raz :)

Żeby skompilować i zainstalować qfaktury na ubuntu 16.4 i jego pochodnych np. linuxmint 18.3 trzeba:

dodać dodatkowe repozytoria:

```
sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial
sudo add-apt-repository ppa:aroth/ppa
sudo add-apt-repository ppa:nschloe/cmake-nightly
sudo add-apt-repository ppa:ondrej/php 

potem

sudo apt-get update
```
następnie zainstalować:

`sudo apt-get install php7.1 php7.1-common zlib1g-dev zlib1g cmake libquazip5-dev qt510-meta-full libgl-dev extra-cmake-modules build-essential`

następnie po kompilacji i instalacji by program się uruchamiał bez problemów >> 

trzeba usunąć główny pakiet qtbase5-dev w wersji 5.5.1 (bez jego usunięcia nie można utworzyć linku symbolicznego, do nowszej wersji qt 5.10 zlokalizowanej w katalogu /opt  (system mówi że nie można utworzyć, bo taki już ustnieje)

`sudo apt-get --purge remove qtbase5-dev`

na końcu wpisujemy: 

`sudo updatedb`

i robimy link symboliczny do qt 5.10

`sudo ln -s /opt/qt510/lib/* /usr/lib/x86_64-linux-gnu/`

To tyle Pozd.

**Comment by sirlucjan** [comment]
To poradnik, zgłoszenie błędu czy jakaś techniczna uwaga ?

**Comment by etammable** [comment]
No nie wiem jak to nazwać (To poradnik, zgłoszenie błędu czy jakaś techniczna uwaga ?), ale jeżeli ktoś będzie chciał zainstalować qfaktury na ubuntu i będzie korzystał z instrukcji instalacji zależności w takiej wersji jaką napisaliści:

>  "sudo apt-get install php7.1 php7.1-common zlib1g-dev zlib1g cmake gksu qtbase5-dev qtwebengine5-dev libquazip-qt5-dev extra-cmake-modules" 

to program mu się nie skompiluje. 
Natomiast według mojej instrukcji wszystko pójdzie gładko  tz: 

```
dodać dodatkowe repozytoria:

sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial
sudo add-apt-repository ppa:aroth/ppa
sudo add-apt-repository ppa:nschloe/cmake-nightly
sudo add-apt-repository ppa:ondrej/php 

potem

sudo apt-get update

następnie zainstalować:

sudo apt-get install php7.1 php7.1-common zlib1g-dev zlib1g cmake libquazip5-dev qt510-meta-full libgl-dev extra-cmake-modules build-essential
```
Z tymi linkami symbolicznymi sprawa jest już bardziej skomplikowana, bo jakoś ta wersja qt 5.10 konliktuje się z defaultowo zainstalowaną 5.5.1, której wymagają inne pakiety, dlatego co do mojej instrukcji w 100% procentach przekonany nie jestem i wiedzy na tyle nie mam by to jakoś rozumnie rozkminić. 

Ps. Jeżeli taki wątek nie mieści się w konwencji github to proszę go usunąć, a ja z góry przepraszam. Pozdrawiam

**Comment by juliagoda** [comment]
> Jak wcześniej mówiłem, napisze taki "mini przewodnik" instalacji na ubuntu/linuxmint i prześlę go na maila juliagoda

Nie dziw mu się, że się zapytał, w końcu to nie tu miał trafić twój poradnik... Dziękuję za poradnik, dodam go do README. Po to został dodany email, aby był w takich przypadkach do dyspozycji i jest on dostępny publicznie. Pozdrawiam

**Comment by sirlucjan** [comment]
To są niestety "plusy ujemne" stosowania dystrybucji wydawniczych takich jak Ubuntu. Dotyczy to także distr LTS. Lista zarzutów jakie mógłbym wobec nich przedstawić jest spora, to jednak nie jest na to odpowiednie miejsce. 

Od biedy można to uznać za błąd (poprawka README.md) jednakże takie rzeczy lepiej załatwiać jest drogą mailową. Uważam, że błąd w README.md nie jest tożsamy z błędem aplikacji (nieprawidłowe działanie bądź ... całkowity brak działania). Adresy e-mail mamy podane w profilu.
