### ISSUE TITLE
Problem przy budowaniu.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#43]
Witam,

Mam problem podczas próby zbudowania najnowszej wersji 7.2. Posiadam system Manjaro, przy próbie zbudowania z:
https://github.com/archlinux-lucjan/archlinux-poland

Wiem, że podczas budowania zwraca wersję "qfaktury-qt5-git 0.7.1.72.gd70f01e-1" ale wydaje mi się, że  autor PKGBUILD, na sztywno wrzucił tą wartość do wersji pakietu. Miałem błąd:
`makepkg -sric
==> Tworzenie pakietu: qfaktury-qt5-git 0.7.1.72.gd70f01e-1 (pon, 5 mar 2018, 20:11:27 CET)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> Pobieranie źródeł...
  -> Klonowanie qfaktury repozytorium git...
Cloning into bare repository '/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/qfaktury'...
remote: Counting objects: 5385, done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 5385 (delta 134), reused 101 (delta 47), pack-reused 5181
Receiving objects: 100% (5385/5385), 68.31 MiB | 5.49 MiB/s, done.
Resolving deltas: 100% (3784/3784), done.
==> Sprawdzanie plików source za pomocą md5sums...
    qfaktury ... Pominięto
==> Rozpakowywanie źródeł...
  -> Tworzenie kopii roboczej repozytorium qfaktury git...
Cloning into 'qfaktury'...
done.
==> Rozpoczynanie prepare()...
==> Rozpoczynanie pkgver()...
==> Zaktualizowana wersja: qfaktury-qt5-git 0.7.2.5.gfcb5d9e-1
==> Rozpoczynanie build()...
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /usr/share/ECM/modules/;/usr/share/ECM/find-modules/;/usr/share/ECM/kde-modules/;/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/cmake/modules;/usr/share/cmake-3.10/Modules
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'quazip'
--   No package 'quazip' found
-- Found QUAZIP: /usr/lib/libquazip5.so  
EN: QuaZip has been found. It's possible to create backup 
PL: Znaleziono QuaZip. Jest możliwe tworzenie kopii zapasowych
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/build
Scanning dependencies of target qfaktury_autogen
make[2]: *** Brak reguł do zrobienia obiektu 'ui_user.h', wymaganego przez 'CMakeFiles/qfaktury_autogen'. Stop.
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/qfaktury_autogen.dir/all] Błąd 2
make: *** [Makefile:130: all] Błąd 2
==> BŁĄD: Wystąpił błąd w build().
    Przerywam...
`

Dokładnie to samo mam w przypadku budowy ręcznie (na innym komputerze z Manjaro), poniżej wycinek:
`[  3%] Building CXX object CMakeFiles/qfaktury.dir/src/mainwindow.cpp.o
In file included from /home/uzytkownik/qfaktury/qfaktury/src/mainwindow.cpp:17:0:
/home/uzytkownik/qfaktury/qfaktury/src/user.h:8:10: fatal error: ui_user.h: Nie ma takiego pliku ani katalogu
 #include "ui_user.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qfaktury.dir/build.make:524: CMakeFiles/qfaktury.dir/src/mainwindow.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/qfaktury.dir/all] Błąd 2
make: *** [Makefile:130: all] Błąd 2
`

**Comment by sirlucjan** [comment]
Odnośnie numeru wersji: budowałeś kiedykolwiek cokolwiek z gita? Mam wrażenie, że nie. Numer wersji jest generowany automatycznie za co odpowiada składnia:

```
pkgver() {
       cd ${_gitname}
       # git tags
       git describe --tags --long | sed 's/^v//;s/-/./g'
       # cmakelist version
       # _ver="$(cat CMakeLists.txt | grep -m3 -e _VERSION_MAJOR -e _VERSION_MINOR -e _VERSION_MICRO | grep -o "[[:digit:]]*" | paste -sd'.')"
       # echo "${_ver}.r$(git rev-list --count HEAD).g$(git rev-parse --short HEAD)"
       }
```

PKGBUILD został wrzucony po zbudowaniu jednego z commitów - numer wersji został nadany na podstawie działania polecenia "git describe" które to do nadawania numeru wersji korzysta z tagów.

**Comment by juliagoda** [comment]
Moja wina. Podczas sprzątania śmieci pociągnęłam o jeden plik za dużo -> user.ui. Teraz było budowane i sprawdzane jeszcze raz po tym.

**Comment by sirlucjan** [comment]
Potwierdzam:

```
==> Sprzątanie instalacji...
  -> Usuwanie libtool plików...
  -> Usuwanie niechcianych plików...
  -> Usuwanie statycznych plików bibliotek
  -> Wyrzucanie niepotrzebnych symboli z plików binarnych i bibliotek
  -> Kompresowanie stron man oraz info...
==> Sprawdzanie problemów pakowania...
==> Tworzenie pakietu "qfaktury-qt5-git"...
  -> Generowanie pliku .PKGINFO...
  -> Generowanie pliku .BUILDINFO...
  -> Generowanie pliku .MTREE...
  -> Kompresowanie pakietu...
==> Podpisywanie pakietu...
  -> Utworzono plik podpisu /home/lucjan/Pobrane/roboczy-1/qfaktury/luc/qfaktury-qt5-git/qfaktury-qt5-git-0.7.2.6.g6ea3012-1-x86_64.pkg.tar.xz.sig.
==> Opuszczanie środowiska fakeroot.
==> Ukończono tworzenie: qfaktury-qt5-git 0.7.2.6.g6ea3012-1 (pon, 5 mar 2018, 21:00:36 CET)
```

**Comment by elzearr** [comment]
sirlucjan - masz rację, nigdy nie budowałem z gita. Nie miałem zamiaru robić niepotrzebnego zamętu, przepraszam. Ja również potwierdzam, pakiet poprawnie się zbudował.
