### ISSUE TITLE
Pole termin płatności - niedostępne.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#44]
Zauważyłem kilka błędów, podczas korzystania z aplikacji. Postaram się je opisać dokładnie i pojedynczo.
W momencie gdy przeniesiemy w ustawieniach / słownik / Forma płatności, przelew na samą górę, pole Termin, będzie wyszarzone (podczas tworzenia faktury):
![image](https://user-images.githubusercontent.com/37084388/36998275-9c34b670-20bc-11e8-8a11-8f3ff4b3dc1a.png)
Aby można było zmienić  wartość w tym polu, trzeba wybrać inną opcję (np. gotówkę) i wrócić do przelewu. 

Dodatkowo, czy istnieje możliwość aby ta wartość (termin) pojawiała się na fakturze? np. dodatkowa linia, z informacją "Termin płatności"?

**Comment by juliagoda** [comment]
Jak jest teraz?

**Comment by elzearr** [comment]
Oba przypadki zostały poprawione, tzn. pole jest automatycznie aktywne oraz pojawia się termin platnosci.
Dzięki!
