### ISSUE TITLE
Pole "Dodatkowy tekst" - problem z formatowaniem tekstu.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#45]
Chcąc wprowadzić sformatowany tekst na fakturze, podczas generowania dokumentu, program nie bierze tego pod uwagę np:
![image](https://user-images.githubusercontent.com/37084388/36998621-d67f0636-20bd-11e8-8e89-a98f4d141f60.png)

output będzie:
![image](https://user-images.githubusercontent.com/37084388/36998712-2a993a70-20be-11e8-907d-1009d86a7344.png)

**Comment by juliagoda** [comment]
Czy teraz jest w porządku?

**Comment by elzearr** [comment]
Tak jak najbardziej, teraz działa to poprawnie.
