### ISSUE TITLE
Aplikacja wyłącza się przy dodawaniu produktu.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#46]
Podczas działania w aplikacji zauważyłem kolejny błąd:
Podczas tworzenia bądź edytowania faktury, wprowadzając z tego miejsca nowy towar bądź usługę (której nie ma na liście) aplikacja się zamyka.
Uruchomiłem aplikację z poziomu terminala i poniżej jest output:

`qfaktury
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/main.cpp :  15 ]  main

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3178:19: not a number

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3178:19: Expected a string.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3571:62: Using one color stop with linear-gradient() is deprecated.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3604:59: Using one color stop with linear-gradient() is deprecated.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3621:61: Using one color stop with linear-gradient() is deprecated.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3637:59: Using one color stop with linear-gradient() is deprecated.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3651:59: Using one color stop with linear-gradient() is deprecated.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gnome-applications.css:288:13: not a number

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: gnome-applications.css:288:13: Expected a string.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: other-applications.css:132:13: not a number

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: other-applications.css:132:13: Expected a string.

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: mate-applications.css:75:13: not a number

(qfaktury:20194): Gtk-WARNING **: Theme parsing error: mate-applications.css:75:13: Expected a string.
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  52 ]  MainWindow
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  110 ]  init
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  614 ]  firstRun
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  966 ]  setupDir
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  516 ]  ifEmergTemplateExists
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  15 ]  XmlDataLayer
application path:  "/usr/local/share/qfaktury"
QUAZIP_FOUND -> It's possible to run connections for Backup
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  887 ]  readBuyer
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  766 ]  tableClear
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  127 ]  buyersSelectAllData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  77 ]  ifPersonNodeExists
node person exists
"person"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  95 ]  addSectionPerson
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 14 BuyerData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  37 ]  buyersElemToData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 14 BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 14 BuyerData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  37 ]  buyersElemToData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 14 BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
liczba kolumn:  7
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
liczba kolumn:  7
liczba kolumn:  7
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
liczba kolumn:  7
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerdata.cpp 19 ~BuyerData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  808 ]  readHist
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1822 ]  invoiceSelectAllData
pliki: 
("h2018-03-05_0.xml", "h2018-03-05_1.xml", "h2018-03-05_2.xml", "h2018-03-06_0.xml")
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 14 CustomPaymData
"h2018-03-05_0.xml"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1405 ]  nameFilter
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 14 CustomPaymData
"h2018-03-05_1.xml"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1405 ]  nameFilter
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 14 CustomPaymData
"h2018-03-05_2.xml"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1405 ]  nameFilter
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 14 CustomPaymData
"h2018-03-06_0.xml"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1405 ]  nameFilter
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  2240 ]  getAllSymbols
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
Added ID of file
Added file name
Added file date
Added file type
Added buyer's name
Added file NIP
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
Added ID of file
Added file name
Added file date
Added file type
Added buyer's name
Added file NIP
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
Added ID of file
Added file name
Added file date
Added file type
Added buyer's name
Added file NIP
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
Added ID of file
Added file name
Added file date
Added file type
Added buyer's name
Added file NIP
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/custompaymdata.cpp 20 ~CustomPaymData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  848 ]  readWarehouses
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  1962 ]  warehouseSelectAllData
pliki: 
()
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  2249 ]  getAllSymbolsWarehouse
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  924 ]  readGoods
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  766 ]  tableClear
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  812 ]  productsSelectAllData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  775 ]  productsElemToData
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  775 ]  insertRow
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  636 ]  categorizeYears
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  2513 ]  ifThereOldDocuments
pliki: 
()
categorizedFiles count first:  0
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/xmldatalayer.cpp :  2513 ]  ifThereOldDocuments
pliki: 
()
categorizedFiles count first:  0
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  559 ]  loadPlugins
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  470 ]  ifpdfDirExists
resources file  "qfaktury.rcc"  is not valid
resources file  "qfaktury.rcc"  is empty
Get STYLE:  "Fusion"
QCommandLineParser: option not defined: "lang"
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  1994 ]  newInv
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  30 ]  Invoice
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  118 ]  init
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
whatTypeFromTitle 275 /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  285 ]  whatTypeFromTitle EXIT
QObject::connect: No such signal QTextEdit::textChanged(QString)
QObject::connect:  (sender name:   'additEdit')
QObject::connect:  (receiver name: 'Invoice')
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1230 ]  payTextChanged
payTextChanged 0
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1357 ]  textChanged
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1361 ]  textChanged EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1347 ]  payTextChanged EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1357 ]  textChanged
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1361 ]  textChanged EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  1141 ]  backBtnClick
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  61 ]  instance
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp :  787 ]  getMaxSymbol
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  2935 ]  numbersCount
nr:  5
sett().value("chars_in_symbol") 0
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  2946 ]  numbersCount EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  268 ]  init EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  56 ]  Invoice EXIT
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  914 ]  getCustomer
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 9 BuyersList
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 20 init
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 157 readBuyer
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 244 xmlDataToString
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 244 xmlDataToString
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 113 updateDetails
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 268 displayDetails
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 113 updateDetails
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 268 displayDetails
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 60 doAccept
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 304 detailsToString
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/buyerslist.cpp 48 getRetBuyerList
[ /home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/invoice.cpp :  980 ]  addGoods
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 18 GoodsList
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 62 init
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 311 readGoods
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 407 displayData
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 276 calcNet
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 276 calcNet
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 276 calcNet
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 276 calcNet
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 276 calcNet
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/goodslist.cpp 175 doAccept
listProducts[0] QHash()
listProducts[1] QHash(("cos", 0x559462a829d0))
Naruszenie ochrony pamięci (zrzut pamięci)`

**Comment by juliagoda** [comment]
Rozumiem, nie wprowadza w obieg danych , które są sztywno ustawiane. To może zapytam tak, bo program jest teraz w trakcie przepisywania. Czy dla Ciebie jako użytkownika byłoby użyteczne dodawanie danych towaru lub usługi w tym miejscu? Jeśli tak, trzeba będzie dodać nową rubrykę z vat, ponieważ w tym momencie brak mu pełnych danych do przeliczania. Jeśli nie, trzeba będzie usunąć możliwość edycji rubryki "Nazwa*", aby wymuszało konieczność zaznaczenia jednego z elementów na liście. Wolny wybór.

**Comment by elzearr** [comment]
Wydaje mi się, że nie jest wymagane tworzenie towaru z tego miejsca. Zauważyłem jedynie podczas testowania różnych opcji, że doprowadziło to do wywrócenia aplikacji. Może wystarczy dodać wyjątek, w którym użytkownik byłby informowany, że należy dodać najpierw towar/usługę w odpowiednim do tego miejscu.

**Comment by juliagoda** [comment]
W takim razie zablokowane
