### ISSUE TITLE
Zakładka Firma - pola opisu są przesunięte

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#47]
W ustawieniach Firma, opisy nie układa się poprawnie względem pól do uzupełniania, od "nr. konta*:" widać to dokładnie:
![image](https://user-images.githubusercontent.com/37084388/37052611-204f3846-217a-11e8-9ad5-2f79ba3b5809.png)

**Comment by juliagoda** [comment]
Czy jest jakoś lepiej?

**Comment by elzearr** [comment]
Nadal od pola "Województwo" pojawia się przesunięcie. Może to być spowodowane czymś u mnie?
![image](https://user-images.githubusercontent.com/37084388/37101787-a8c963c0-2226-11e8-9757-b89cc1ac1b68.png)

**Comment by juliagoda** [comment]
Stawiam, że nie. Mam pomysł na inny sposób ułożenia, który powinien ten problem w końcu zażegnać. Jutro tym się zajmę.

**Comment by juliagoda** [comment]
Czy teraz jest w porządku i program się kompiluje?

**Comment by elzearr** [comment]
Tak, program się skompilował i wszystko wygląda poprawnie:
![image](https://user-images.githubusercontent.com/37084388/37214662-f3f68e1e-23b5-11e8-820f-5588b0c03498.png)
