### ISSUE TITLE
Układ wydruku - dodatkowe informacje na fa.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#48]
Zauważyłem, że program dokleja na końcu dokumentu dodatkową adnotację:

![image](https://user-images.githubusercontent.com/37084388/37053827-8384a330-217d-11e8-8ce5-bd424d4cc79c.png)

Na tyle na ile się orientuję, ten tekst nie jest wymagany w tej formie jeżeli faktury będą przesyłane drogą elektroniczną (a nawet niewskazane). Oczywiście forma "Imię i Nazwisko osoby upoważnionej do wystawienia faktury VAT" musi się znaleźć, ale może być tam uzupełnione elektronicznie imię i nazwisko bez pola osoby potwierdzającej odbiór.
Czy można by dodać kolejne pole wyboru podczas wystawiania FA, aby taki dopisek był generowany bądź nie, lub możliwość jego edycji?

**Comment by juliagoda** [comment]
Czy o to chodziło? Trzeba załączyć podpis w ustawieniach w zakładce "Ogólne"

**Comment by elzearr** [comment]
Chodziło mi raczej o możliwość edytowania dodawanego tekstu doklejanego do podglądu wydruku, lub możliwość włączania i wyłączania tych dwu informacji przed np wystawieniem fa. W momencie wystawiania fa przy odbiorze osobistym, pole "Imię i nazwisko osoby upoważnionej do odbioru faktury VAT" jest przydatne.

**Comment by juliagoda** [comment]
Teraz dodano obok innych opcji jak "Wyłącz walidację" dwie oddzielne opcje, jedna dla podpisu odbioru faktury a druga do podpisu wystawienia. Czy o to chodzi? Czy coś podobnego?

**Comment by elzearr** [comment]
Tak dokładnie!! Bardzo dziękuję.
