### ISSUE TITLE
problem przy budowaniu.

### ISSUE THREAD

**Issue by elzearr** [juliagoda/qfaktury#49]
Po ostatnich zmianach nie mogę zbudować pakietu, info z terminala:

`[ 45%] Building CXX object CMakeFiles/qfaktury.dir/src/mainwindow.cpp.o
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp: In destructor ‘virtual MainWindow::~MainWindow()’:
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:93:7: error: ‘plugActions’ was not declared in this scope
   if (plugActions.count() > 0) {
       ^~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:93:7: note: suggested alternative: ‘addActions’
   if (plugActions.count() > 0) {
       ^~~~~~~~~~~
       addActions
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp: In member function ‘void MainWindow::init()’:
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:401:3: error: ‘loadPlugins’ was not declared in this scope
   loadPlugins();
   ^~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp: At global scope:
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:557:30: error: no ‘void MainWindow::loadPlugins()’ member function declared in class ‘MainWindow’
 void MainWindow::loadPlugins() {
                              ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:663:59: error: no ‘int MainWindow::getInvoiceTypeFullName(QString)’ member function declared in class ‘MainWindow’
 int MainWindow::getInvoiceTypeFullName(QString invoiceType) {
                                                           ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:1059:33: error: no ‘void MainWindow::pluginInfoSlot()’ member function declared in class ‘MainWindow’
 void MainWindow::pluginInfoSlot() {
                                 ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:1075:29: error: no ‘void MainWindow::pluginSlot()’ member function declared in class ‘MainWindow’
 void MainWindow::pluginSlot() {
                             ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2509:39: error: no ‘void MainWindow::createFirstWinBackup()’ member function declared in class ‘MainWindow’
 void MainWindow::createFirstWinBackup() {
                                       ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp: In member function ‘void MainWindow::intervalBackup()’:
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2600:7: error: ‘createBackupWithoutGUI’ was not declared in this scope
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2600:7: note: suggested alternative: ‘createBackupMode’
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
       createBackupMode
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2604:7: error: ‘createBackupWithoutGUI’ was not declared in this scope
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2604:7: note: suggested alternative: ‘createBackupMode’
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
       createBackupMode
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2608:7: error: ‘createBackupWithoutGUI’ was not declared in this scope
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2608:7: note: suggested alternative: ‘createBackupMode’
       createBackupWithoutGUI();
       ^~~~~~~~~~~~~~~~~~~~~~
       createBackupMode
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2610:7: error: ‘createBackupWithoutGUI’ was not declared in this scope
       createBackupWithoutGUI(); // It's sure that will be in minutes or hours
       ^~~~~~~~~~~~~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2610:7: note: suggested alternative: ‘createBackupMode’
       createBackupWithoutGUI(); // It's sure that will be in minutes or hours
       ^~~~~~~~~~~~~~~~~~~~~~
       createBackupMode
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2613:5: error: ‘createBackupWithoutGUI’ was not declared in this scope
     createBackupWithoutGUI(); // just create backup. Needed if user starts
     ^~~~~~~~~~~~~~~~~~~~~~
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2613:5: note: suggested alternative: ‘createBackupMode’
     createBackupWithoutGUI(); // just create backup. Needed if user starts
     ^~~~~~~~~~~~~~~~~~~~~~
     createBackupMode
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp: At global scope:
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2624:37: error: no ‘QString MainWindow::whichBackupPath()’ member function declared in class ‘MainWindow’
 QString MainWindow::whichBackupPath() {
                                     ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2647:41: error: no ‘void MainWindow::createBackupWithoutGUI()’ member function declared in class ‘MainWindow’
 void MainWindow::createBackupWithoutGUI() {
                                         ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2709:35: error: no ‘void MainWindow::choosePathBackup()’ member function declared in class ‘MainWindow’
 void MainWindow::choosePathBackup() {
                                   ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2726:31: error: no ‘void MainWindow::createBackup()’ member function declared in class ‘MainWindow’
 void MainWindow::createBackup() {
                               ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2785:29: error: no ‘void MainWindow::loadBackup()’ member function declared in class ‘MainWindow’
 void MainWindow::loadBackup() {
                             ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:2972:36: error: no ‘void MainWindow::createFirstWinCsv()’ member function declared in class ‘MainWindow’
 void MainWindow::createFirstWinCsv() {
                                    ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3032:32: error: no ‘void MainWindow::choosePathCsv()’ member function declared in class ‘MainWindow’
 void MainWindow::choosePathCsv() {
                                ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3045:33: error: no ‘void MainWindow::createCsvFiles()’ member function declared in class ‘MainWindow’
 void MainWindow::createCsvFiles() {
                                 ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3110:39: error: no ‘void MainWindow::createBuyersCsvFiles()’ member function declared in class ‘MainWindow’
 void MainWindow::createBuyersCsvFiles() {
                                       ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3193:41: error: no ‘void MainWindow::createProductsCsvFiles()’ member function declared in class ‘MainWindow’
 void MainWindow::createProductsCsvFiles() {
                                         ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3287:40: error: no ‘void MainWindow::createSellersCsvFiles()’ member function declared in class ‘MainWindow’
 void MainWindow::createSellersCsvFiles() {
                                        ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3452:61: error: no ‘void MainWindow::createInvoicesCsvFiles(QDate, QDate)’ member function declared in class ‘MainWindow’
 void MainWindow::createInvoicesCsvFiles(QDate from, QDate to) {
                                                             ^
/home/user/faktury_test/archlinux-poland/qfaktury-qt5-git/src/qfaktury/src/mainwindow.cpp:3650:57: error: no ‘void MainWindow::createWareCsvFiles(QDate, QDate)’ member function declared in class ‘MainWindow’
 void MainWindow::createWareCsvFiles(QDate from, QDate to) {
                                                         ^
make[2]: *** [CMakeFiles/qfaktury.dir/build.make:536: CMakeFiles/qfaktury.dir/src/mainwindow.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/qfaktury.dir/all] Błąd 2
make: *** [Makefile:130: all] Błąd 2
==> BŁĄD: Wystąpił błąd w build().
    Przerywam...
`

**Comment by juliagoda** [comment]
Proszę sprawdzić znów przy wolnym czasie. Buduję zawsze konsolowo i w IDE przed każdym wrzuceniem, a jednak i tak potem wychodzą błędy dnia następnego. Jeszcze na razie nie doszłam do tego, co to powoduje...

**Comment by elzearr** [comment]
Teraz zbudowałem bez problemów. Dziękuję, działa.
