### ISSUE TITLE
[Solved] Manjaro - problem z interfejsem programu.

### ISSUE THREAD

**Issue by sabbath88** [juliagoda/qfaktury#5]
Świeża instalacja Manjaro XFCE 64bit, zaktualizowana.
qt5-base 5.8.0-11
qt5-webengine 5.8.0-8
Stan jak na zrzucie ekranu: 
http://imgur.com/a/DkqZi
http://imgur.com/a/mLJUQ
Czy może ktoś podpowiedzieć co jest nie tak?

**Comment by juliagoda** [comment]
Miałam na Manjaro ten sam problem, musisz zmienić w programie domyślny motyw. Jak go zmienisz to będzie po restarcie programu ok. Z tego co pamiętam to właśnie ten motyw tylko sprawiał takie problemy. Daj znać jak poszło.

**Comment by juliagoda** [comment]
Program -> Ustawienia i pojawi się pierwsza zakładka, w której można zmieniać motyw programu.

**Comment by sabbath88** [comment]
Wielkie dzięki za pomoc. Teraz wygląda doskonale. Nie wiem czy inny użytkownicy mają w zwyczaju przeglądać zamknięte zgłoszenia. W razie czego polecam dorzucić informację do rozwiązania gdzieś w okolicy instrukcji instalacji. 

ps. Można też ustawić by program domyślnie korzystał z mniej problematycznej skórki.
Pozdrawiam i jeszcze raz serdecznie dziękuje za pomoc.

**Comment by juliagoda** [comment]
Uwzględnię w instrukcji co zrobić w przypadku gdy jest obecny ten problematyczny motyw lub co myślę będzie dużo lepsze, zablokowanie tego motywu na liście i wybranie np. kolejnego występującego po nim tak jak napisałeś. Zrobię to po weekendzie. Dzięki za uwagę i nie ma sprawy
