### ISSUE TITLE
Problem podczas instalacji.

### ISSUE THREAD

**Issue by sabbath88** [juliagoda/qfaktury#51]
Niestety życie zmusiło mnie do przeinstalowania systemu. Obecnie posiadam Manjaro w wersji 17.1.11 (aktualny na dzień dzisiejszy)

[marian@compaq zbudowane]$ uname -a
Linux compaq 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux

Zależności zainstalowane w wersji full.

> [marian@compaq zbudowane]$ cmake ..
> -- The C compiler identification is GNU 8.1.1
> -- The CXX compiler identification is GNU 8.1.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- /usr/share/ECM/modules/;/usr/share/ECM/find-modules/;/usr/share/ECM/kde-modules/;/home/marian/qfaktury/cmake/modules;/usr/share/cmake-3.11/Modules
> CMake Warning at CMakeLists.txt:33 (find_package):
>   By not providing "FindQuaZip5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "QuaZip5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "QuaZip5" with any
>   of the following names:
> 
>     QuaZip5Config.cmake
>     quazip5-config.cmake
> 
>   Add the installation prefix of "QuaZip5" to CMAKE_PREFIX_PATH or set
>   "QuaZip5_DIR" to a directory containing one of the above files.  If
>   "QuaZip5" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> EN: QuaZip hasn't been found in FindQuaZip5.cmake. It's not possible to create backup. 
> PL: Brak biblioteki dla QuaZip. Tworzenie kopii zapasowych zablokowane
> NEXT STEP OF QUAZIP SEARCHING 
> EN: Could NOT find optional library quazip. PL: Nie można znaleźć biblioteki quazip w kolejnym kroku. Możliwość tworzenia backup jest zablokowana.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/marian/qfaktury/zbudowane

> [marian@compaq zbudowane]$ make
> Scanning dependencies of target qfaktury_autogen
> [  1%] Automatic MOC for target qfaktury
> [  1%] Built target qfaktury_autogen
> [  3%] Generating qrc_qfaktury.cpp
> [  5%] Generating ui_setting.h
> [  7%] Generating ui_user.h
> [  8%] Generating ui_mainwindow.h
> [ 10%] Generating ui_invoice.h
> [ 12%] Generating ui_goodslist.h
> [ 14%] Generating ui_goods.h
> [ 16%] Generating ui_custompaymentdialog.h
> [ 17%] Generating ui_changeamount.h
> [ 19%] Generating ui_buyers.h
> [ 21%] Generating ui_buyerslist.h
> [ 23%] Generating ui_organizer.h
> [ 25%] Generating ui_saftfile.h
> [ 26%] Generating ui_backup.h
> [ 28%] Generating ui_csvexport.h
> [ 30%] Generating ui_emailwindow.h
> Scanning dependencies of target qfaktury
> [ 32%] Building CXX object CMakeFiles/qfaktury.dir/src/xmldatalayer.cpp.o
> [ 33%] Building CXX object CMakeFiles/qfaktury.dir/src/buyerdata.cpp.o
> [ 35%] Building CXX object CMakeFiles/qfaktury.dir/src/custompaymdata.cpp.o
> [ 37%] Building CXX object CMakeFiles/qfaktury.dir/src/custompayment.cpp.o
> [ 39%] Building CXX object CMakeFiles/qfaktury.dir/src/correctgross.cpp.o
> [ 41%] Building CXX object CMakeFiles/qfaktury.dir/src/goodsgrosslist.cpp.o
> [ 42%] Building CXX object CMakeFiles/qfaktury.dir/src/bill.cpp.o
> [ 44%] Building CXX object CMakeFiles/qfaktury.dir/src/invoicegross.cpp.o
> [ 46%] Building CXX object CMakeFiles/qfaktury.dir/src/duplicate.cpp.o
> [ 48%] Building CXX object CMakeFiles/qfaktury.dir/src/convertamount.cpp.o
> [ 50%] Building CXX object CMakeFiles/qfaktury.dir/src/invoice.cpp.o
> [ 51%] Building CXX object CMakeFiles/qfaktury.dir/src/buyers.cpp.o
> [ 53%] Building CXX object CMakeFiles/qfaktury.dir/src/buyerslist.cpp.o
> [ 55%] Building CXX object CMakeFiles/qfaktury.dir/src/correction.cpp.o
> [ 57%] Building CXX object CMakeFiles/qfaktury.dir/src/main.cpp.o
> [ 58%] Building CXX object CMakeFiles/qfaktury.dir/src/mainwindow.cpp.o
> [ 60%] Building CXX object CMakeFiles/qfaktury.dir/src/goods.cpp.o
> [ 62%] Building CXX object CMakeFiles/qfaktury.dir/src/goodslist.cpp.o
> [ 64%] Building CXX object CMakeFiles/qfaktury.dir/src/setting.cpp.o
> [ 66%] Building CXX object CMakeFiles/qfaktury.dir/src/user.cpp.o
> [ 67%] Building CXX object CMakeFiles/qfaktury.dir/src/changeamount.cpp.o
> [ 69%] Building CXX object CMakeFiles/qfaktury.dir/src/validations.cpp.o
> [ 71%] Building CXX object CMakeFiles/qfaktury.dir/src/invoicerr.cpp.o
> [ 73%] Building CXX object CMakeFiles/qfaktury.dir/src/SimpleSmtp_SSL_QT5/smtp_attachements/emailwindow.cpp.o
> [ 75%] Building CXX object CMakeFiles/qfaktury.dir/src/SimpleSmtp_SSL_QT5/smtp_attachements/smtp.cpp.o
> [ 76%] Building CXX object CMakeFiles/qfaktury.dir/src/send.cpp.o
> [ 78%] Building CXX object CMakeFiles/qfaktury.dir/src/owncalendar.cpp.o
> [ 80%] Building CXX object CMakeFiles/qfaktury.dir/src/warehouse.cpp.o
> [ 82%] Building CXX object CMakeFiles/qfaktury.dir/src/deliverynote.cpp.o
> [ 83%] Building CXX object CMakeFiles/qfaktury.dir/src/goodsissuednotes.cpp.o
> [ 85%] Building CXX object CMakeFiles/qfaktury.dir/src/organizer.cpp.o
> [ 87%] Building CXX object CMakeFiles/qfaktury.dir/src/saftfile.cpp.o
> /home/marian/qfaktury/src/saftfile.cpp: In destructor ‘virtual Saftfile::~Saftfile()’:
> /home/marian/qfaktury/src/saftfile.cpp:74:12: error: possible problem detected in invocation of delete operator: [-Werror=delete-incomplete]
>      delete groupAppPurp;
>             ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:74:12: error: invalid use of incomplete type ‘class QButtonGroup’ [-Werror]
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:74:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
>      delete groupAppPurp;
>             ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:75:12: error: possible problem detected in invocation of delete operator: [-Werror=delete-incomplete]
>      delete groupArtFiles;
>             ^~~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:75:12: error: invalid use of incomplete type ‘class QButtonGroup’ [-Werror]
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:75:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
>      delete groupArtFiles;
>             ^~~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp: In member function ‘void Saftfile::showConnections()’:
> /home/marian/qfaktury/src/saftfile.cpp:86:75: error: incomplete type ‘QButtonGroup’ used in nested name specifier
>      connect(groupAppPurp, QOverload<QAbstractButton *>::of(&QButtonGroup::buttonPressed),
>                                                                            ^~~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp: In member function ‘void Saftfile::putBtnToGroup()’:
> /home/marian/qfaktury/src/saftfile.cpp:115:37: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupAppPurp = new QButtonGroup();
>                                      ^
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:116:17: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupAppPurp->addButton(ui->correctionAppBtn);
>                  ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:117:17: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupAppPurp->addButton(ui->standardAppBtn);
>                  ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:119:38: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupArtFiles = new QButtonGroup();
>                                       ^
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:120:18: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupArtFiles->addButton(ui->saftJPKVATbtn);
>                   ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp:121:18: error: invalid use of incomplete type ‘class QButtonGroup’
>      groupArtFiles->addButton(ui->saftJPKFAbtn);
>                   ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp: In member function ‘const QString Saftfile::getApplicationPurpose()’:
> /home/marian/qfaktury/src/saftfile.cpp:149:32: error: invalid use of incomplete type ‘class QButtonGroup’
>      QString text = groupAppPurp->checkedButton()->text();
>                                 ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp: In member function ‘const QString Saftfile::getJpkFileArtWithVersion()’:
> /home/marian/qfaktury/src/saftfile.cpp:158:33: error: invalid use of incomplete type ‘class QButtonGroup’
>      QString text = groupArtFiles->checkedButton()->text();
>                                  ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> /home/marian/qfaktury/src/saftfile.cpp: In member function ‘const QString Saftfile::getJpkFileArt()’:
> /home/marian/qfaktury/src/saftfile.cpp:170:33: error: invalid use of incomplete type ‘class QButtonGroup’
>      QString text = groupArtFiles->checkedButton()->text();
>                                  ^~
> In file included from /home/marian/qfaktury/src/saftfile.cpp:1:
> /home/marian/qfaktury/src/saftfile.h:14:7: note: forward declaration of ‘class QButtonGroup’
>  class QButtonGroup;
>        ^~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> make[2]: *** [CMakeFiles/qfaktury.dir/build.make:579: CMakeFiles/qfaktury.dir/src/saftfile.cpp.o] Błąd 1
> make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/qfaktury.dir/all] Błąd 2
> make: *** [Makefile:130: all] Błąd 2
> [marian@compaq zbudowane]$

**Comment by sirlucjan** [comment]
Przeczytałeś opis programu? Aplikacja nie jest już rozwijana, zgłaszanie błędów mija się więc z celem.

**Comment by sabbath88** [comment]
Witaj, wiem że aplikacja nie jest już rozwijana. Ale czy to znaczy że pozostawiony kod nie nadaje się do kompilacji i instalacji? Utworzyłem zgłoszenie ponieważ być może robię jakiś głupi lub dość oczywisty błąd. Dotychczas aplikacja sprawowała się świetnie. Pomimo tego że nie jest rozwijana, to nadal chciałbym z niej korzystac. Do podstawowych działań nadaje się wyśmienicie. Może i nie jest rozwijanam ale moze jakies wsparcie instalacyjne się znajdzie (nawet jeśli nie za darmo).
Pozdrawiam

**Comment by juliagoda** [comment]
Jak jest teraz?

**Comment by sabbath88** [comment]
@juliagoda teraz zainstalowało się poprawnie. Dziękuję bardzo za pomoc. Gdzie można przekazać datki w podzięce ? (;

**Comment by juliagoda** [comment]
Naprawdę nie trzeba, bo nawet to nie zalicza się do napisania skryptu, jeśli chodzi o poziom zaawansowania. Nie chcę kasować pieniądze za 5 minut roboty.
