### ISSUE TITLE
[Request] Nowy typ kontrahenta - Osoba fizyczna

### ISSUE THREAD

**Issue by sabbath88** [juliagoda/qfaktury#6]
Witam.
W kontrahentach brakuje typu: Osoba fizyczna.
Należy uwzględnić że przy takim typie należy znieść walidacje pola "NIP", które nie jest wymagane.
Myślę że pola "Miejscowość", "Kod", "Adres" również nie wymagają walidacji w przypadku osób fizycznych (w razie wątpliwości mogę skonsultować to z księgową).

**Comment by juliagoda** [comment]
Została dodana osoba fizyczna z uwzględnieniem walidacji numeru NIP, jeśli chodzi o pozostałe rubryki to póki co je pozostawię. Szukałam informacji i wynikało z tego, że o ile numer PESEL nie jest obligatoryjny to adres powinien być, ale mimo wszystko to są strony internetowe i jeżeli faktycznie księgowa powiedziałaby inaczej, to wtedy to zmienię. Sama jeszcze o to zapytam księgowego.

**Comment by sabbath88** [comment]
Księgowa potwierdziła że adres powinien zostać.
Ma to zastosowanie np.: w przypadku firm, które nie są podatnikiem VATu oraz nie posiadają kasy fiskalnej.
W takim przypadku rachunek powinien dosyć jasno wskazywać na kogo został wystawiony.
Jako że nie stosuje się już NIPu dla osób fizycznych, a pesel nie jest obligatoryjny, to pozostaje uszczegółowienie w formie adresu. 
Dobra robota :)

ps. Przy NIPie powinna zniknąć gwiazdka.

**Comment by juliagoda** [comment]
A myślałam że znika. Przyjrzę się temu w bliższym czasie

**Comment by juliagoda** [comment]
Poprawione, czy teraz jest ok?

**Comment by sabbath88** [comment]
Działa poprawnie.
