### ISSUE TITLE
Szablon wydruku rachunku/faktury

### ISSUE THREAD

**Issue by sabbath88** [juliagoda/qfaktury#7]
Witam.
Poszukuje możliwości edycji szablonów wydruków rachunku i faktury.
W moim przypadku niektóre elementy są zbędne np.: "Ogółem stawki", wymagane jest ujednolicenie wielkości czcionki, oraz rozmieszczenie elementów - bo gniotą się po lewej stronie (; Dodatkowo po dodaniu logo, część tekstu przechodzi na kolejną stronę.

http://imgur.com/a/1VW2x

Będę wdzięczny za wskazówki gdzie można dokonać takich modyfikacji.

**Comment by juliagoda** [comment]
Czy możesz sprawdzić czy jest teraz tak jak powinno być?

**Comment by sabbath88** [comment]
Dziękuję za szybką interwencję.
W środowisku testowym, które w zasadzie jest praktycznie nie skonfigurowanym programem, wygląda to bardzo obiecująco. Wieczorem sprawdzę już konkretnie i dam znać.

**Comment by sabbath88** [comment]
Wygląda ok. Jedynie co można się zmienić to szerokość  kolumny "Nazwa".
W moim przypadku używane kolumny to "Lp.", "Nazwa", "Kod", "Ilość", "jm.", "Cena jedn.", "Wartość Netto", "Wartość Brutto". Zostaje więc dużo miejsca. Tabelka jest ściśnięta do prawej. 
Jeśli to możliwe można to zrobić:
- tabelka 100% szerokość strony, 
- kolumny standardowo określona stała szerokość (czyli tak jak do tej pory),
- wyjątek kolumna "Nazwa", tu szerokość byłoby uzależniona od pozostałego miejsca.

Obecnie wygląda to tak: http://imgur.com/a/JOeaZ

**Comment by juliagoda** [comment]
Czyli jednak. Wahałam się między tymi dwoma wyglądami rubryk tabeli, no cóż, nie trafiłam. Zmienię to też w bliższym czasie

**Comment by juliagoda** [comment]
Czy teraz jest w porządku?

**Comment by sabbath88** [comment]
Wydaje mi się że teraz jest już wszystko dobrze.
