### ISSUE TITLE
Wadliwe działanie weryfikatora NIP

### ISSUE THREAD

**Issue by pavbaranov** [juliagoda/qfaktury#8]
Po wprowadzeniu weryfikacji NIP nie istnieje możliwość dodania żadnego kontrahenta, albowiem program stwierdza, że numer jest wadliwy ("sprawdź kolejność wpisanych cyfr"), a ten jest prawidłowy.
Jedyne obejście, to edycja pliku ~/.local/share/data/elinux/customers.xml i "ręczne" dodanie danych kontrahenta do tego pliku. Program go widzi i interpretuje prawidłowo.

**Comment by juliagoda** [comment]
To faktycznie trochę dziwne. Szukam jakichś dodatkowych informacji na ten temat. Zrobiłam tak jak Ty, tyle że dodałam wadliwy numer NIP bezpośrednio do pliku kontrahenta i wtedy już go faktycznie nie sprawdza. Jednak po dodaniu swojego numeru podczas działania programu, generowanych w internecie czy realnych używanych przez szkoły, banki czy dowolne firmy, suma kontrolna działa poprawnie i numer NIP się przyjmuje. Czy jest więc możliwe, że ktoś otrzymał zły numer NIP lub podał numer zmyślony? Czy ten sam błąd występuje na innych walidatorach? Czy tylko dla tej jednej osoby/firmy ten błąd wystąpił? Czy jest to polski numer? Jeśli wszystko jest w porządku, to musi istnieć inne wytłumaczenie, o którym nie ma informacji w internecie (a może nie trafiłam) to można wyłączyć sprawdzanie sumy kontrolnej ze względu na takie sytuacje jak ta, które mogą się w przyszłości znów pojawić.

**Comment by pavbaranov** [comment]
Cóż... nie odpowiem Ci czy klient podał mi prawidłowy NIP. Sprawdzę na innych. Up2U, ale dla testów wyślij mi swój i Lucka np. na mail. Zobaczymy co i jak.
EDIT:
W sumie... jest możliwe, że klient podał wadliwy NIP. Sprawdziłem teraz inny i bez problemu się dodał. Muszę ustalić co i jak. Odezwę się.

**Comment by juliagoda** [comment]
Ok

**Comment by juliagoda** [comment]
Paweł, czy masz już jakieś informacje na ten temat?

**Comment by pavbaranov** [comment]
Nie, nie mam. Generalnie przydałaby się chyba w programie możliwość
wyłączania weryfikacji.
Pozdrawiam - PB

2017-08-05 15:24 GMT+02:00 juliagoda <notifications@github.com>:
