### ISSUE TITLE
Rozgraniczenie faktur na duplikat, kopię i oryginał jest zbędne

### ISSUE THREAD

**Issue by travnick** [juliagoda/qfaktury#9]
Przepisy nie wymagają takiego rozgraniczenia
http://www.przepisy.gofin.pl/przepisy,4,32,32,670,,20150909,ustawa-z-dnia-11032004-r-o-podatku-od-towarow-i-uslug.html#P66246

_Wymagane to było do dnia wejścia w życie Rozporządzenia Ministra Finansów z dnia 3 grudnia 2013 r. w sprawie wystawiania faktur._

**Comment by juliagoda** [comment]
Dziękuję za uwagę, tym jak i poprawą kodu zajmę się po przeprowadzce, załatwianiu spraw urzędowych i wielu innych jakoś w tym lub następnym tygodniu

**Comment by juliagoda** [comment]
Po głębszym przemyśleniu stwierdziłam, że nie będę tego zmieniać. Każdy użytkownik ma wybór i nie musi używać ani duplikatu ani kopii, ponieważ kopię może wyłączyć w ustawieniach. Oczywiście, że jak bym się miała kierować wygodą to zrobiłabym to w ciemno, bo wykastrowanie programu z tych rzeczy odjęłoby mi sporo pracy, jednak wczuwając się w rolę użytkownika końcowego chciałabym mieć możliwość wyboru. Są też osoby, które posiadają na komputerze pliki z za czasów Qt4 a nawet Qt3. Co jeśli będą chcieli te pliki podejrzeć? Jak się zachowa program a jak ma się zachować? Czy nie lepiej posiadać kompatybilność wsteczną przy tak ważnej rzeczy jaką są faktury? Prócz własnych pomysłów opieram się też na istniejących stronach internetowych (za wczesną zgodą administratorów), które prowadzą za rękę przez fakturowanie i one także dają możliwość takiego wyboru.

Inna sprawa dotycząca const i po co ona. Praktyki jakiej się uczyłam to taka, że dobrze byłoby rozdzielić zmienne na prywatne, a jeśli chce się mieć dostęp do ich danych bez destrukcyjnego wpływu z poziomu innej klasy, tym bardziej nie spokrewnionej, tworzy się metodę, za pomocą której odczytuje się wartość zmiennej bez możliwości jej zmiany. Nie byłam tylko pewna czy const z przodu też wypadałoby dodawać. Ten pomysł nie jest moim widzimisię, ale często stosowaną praktyką przez ludzi, którzy coś już znaczą w świecie programowania i po zastanowieniu ma to sens. Oczywiście jednocześnie nie stwierdzam, że cały kod jest cacy, bo nie jest i wymaga dużo poprawek w wielu miejscach, a na pewno w szczególności wyeliminowanie powielonego kodu, który mógłby zostać szablonem z możliwością podstawiania różnych wartości. Ale nic nie stoi na przeszkodzie, żebyś takie zmiany zastosował we własnym forku i życzę powodzenia, tymczasem zamykam temat i zabieram się za obowiązki

**Comment by travnick** [comment]
@juliagoda proszę o kontakt mailowy.
Chciałbym wprowadzić kilka usprawnień, mógłbym je robić tylko dla siebie ale prawdopodobnie efektywniej będzie jeżeli program rozwijać będzie więcej osób.

**Comment by travnick** [comment]
@juliagoda 
Odnośnie [const correctness](https://isocpp.org/wiki/faq/const-correctness) to tak, zastosowanie ma jak najbardziej sens. Nie mniej w kodzie który odziedziczyłaś (jak widzę po commitach) są błędy:

np:
https://github.com/juliagoda/qfaktury/blob/f9394f49405205fbfb839d6aca8b7a5a4e94c9e3/src/Invoice.cpp#L73
`const` jest umieszczony w złym miejscu i nie ma sensu. `const` Powinien być umieszczony za `Invoice::getRet()` => `Invoice::getRet() const`

inny przykład, których jest też kilka:
https://github.com/juliagoda/qfaktury/blob/54d46cbea2cf57b08b7237a086bdbbd5ddc0d864/src/Correction.cpp#L28
metoda zwraca stałą wartość co wymusza na programiście zrobienia nowej zmiennej jeżeli chce modyfikować zwrócony obiekt (który i tak jest już niezależną kopią tego co zwróciła klasa).
